### ISSUE TITLE
Can I centrally fund transactions fees of my asset(Token) holders

### ISSUE THREAD

**Issue by amitsharma8891** [binance-chain/node-binary#100]
Hi,

If I created a Token on binance Chain, can I fund the transaction fee of users' wallets that hold tokens/assets issued by me?

**E.g:**
I created Token "X" now 500 people have token "X" in their wallets. 
**Let's assume** 
20 people wanted to send these tokens to other wallets
**In this scenario:**
Can I use my token issuing wallet to fund their transactions fees?

Since all fees are to be paid in BNB and my token holder might not have BNB in their wallet.

Thanks.

**Comment by huangsuyu** [comment]
Hello, @amitsharma8891 

Please see the discussion on forum: https://github.com/binance-chain/javascript-sdk/issues/195
