### ISSUE TITLE
0.6.1 full node crased at 26933704 

### ISSUE THREAD

**Issue by freddieee** [binance-chain/node-binary#101]
I used the default config file from 0.6.1. and every time it crashed at the same height

panic: Failed to process committed block (26933704:6AD4DCC0D33974CE364341FB3A373638359BD4BDE20C4FE587B9A54D27A5E4EE): Wrong Block.Header.AppHash.  Expected E2CD97D5398D3345434DC2D6EA418BCBC1DA695A2AE87F211684713868F0A7D6, got C2D620B3C26531A621505DA6CE90830D788850376594865146002881B0893A58

goroutine 30599 [running]:

 github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc002e9c820)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:372 +0x1874
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).SwitchToBlockchain
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:144 +0x326
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected E2CD97D5398D3345434DC2D6EA418BCBC1DA695A2AE87F211684713868F0A7D6, got C2D620B3C26531A621505DA6CE90830D788850376594865146002881B0893A58

**Comment by huangsuyu** [comment]
Hello, @freddieee 

Can you make sure that you have replaced both `app.toml` & `config.toml` .

**Comment by freddieee** [comment]
> Hello, @freddieee
> 
> Can you make sure that you have replaced both `app.toml` & `config.toml` .

Thanks, I started the node from a early snapshot and it worked. I think the problem might be caused by I set state_synced for a full node
