### ISSUE TITLE
Full node cannot catch latest height

### ISSUE THREAD

**Issue by qiluge** [binance-chain/node-binary#102]
That's my config:
![image](https://user-images.githubusercontent.com/19525062/63012099-34c58600-bebc-11e9-95e9-f4a678ca24bd.png)
![image](https://user-images.githubusercontent.com/19525062/63012104-368f4980-bebc-11e9-9f44-043a8f2221e5.png)

That's my full node log:
![image](https://user-images.githubusercontent.com/19525062/63012183-62aaca80-bebc-11e9-955c-5004487a37b8.png)

The node always cannot catch latest height of mainnet. And the gap between my node and mainnet height is getting bigger and bigger. In the other hands, the testnet sync always stuck, it cannot sync block.

**Comment by huangsuyu** [comment]
hello,  @qiluge 

How many peers can you connect with? and can you share configuration info of your server please? thanks!

**Comment by qiluge** [comment]
I am sorry. Using higher I/O speed SSD resoled this problem.
