### ISSUE TITLE
Why cannot query the order information from local api server?

### ISSUE THREAD

**Issue by freddieee** [binance-chain/node-binary#103]
Hi,  according to the document, the order meta data can be queried from ``/api/vi/orders/{orderId}``,  which is accessible in  https://dex.binance.org and the three accelerated nodes, but why it doesn't work in our own full node? Will you also make it available as an extension in the future version?

**Comment by huangsuyu** [comment]
Hello, @freddieee 

The trade info is  only provided by [accelerated nodes](https://docs.binance.org/faq.html#what-is-the-accelerated-node).
