### ISSUE TITLE
Rate limit of public API

### ISSUE THREAD

**Issue by YordanPavlov** [binance-chain/node-binary#104]
I am building a system to query data from the BNB Public API at:

> https://explorer.binance.org/api/v1

at some point I get blocked with:

```
Request blocked.

<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: tAZDMhWK5TKX2EfJcSkp6zLW_tKXb_3zh8Z94SGwVzu0vZn8pI36Kw==
</PRE>
```

The reason I am using the public API is because I am having problem decoding the Amino transactions if I run my own Node. I am trying to do it in JS but no good library is available. What would be the best approach?

1. What is the request rate limit I must obey at  https://explorer.binance.org/api/v1
2. I presume there is no way to subscirbe with Websocket for past transactions? Is that so?
3. Are there another public Nodes providing decoded transaction responses?

Regards!

**Comment by huangsuyu** [comment]
Hello, @YordanPavlov 
Please take a look at js-sdk: https://github.com/binance-chain/javascript-sdk to learn how to decode transactions. 
you can read about the rate limit here: https://docs.binance.org/api-reference/dex-api/paths.html
