### ISSUE TITLE
node start error ( testnet version 0.6.1)

### ISSUE THREAD

**Issue by chaonan1992** [binance-chain/node-binary#108]
panic: Value missing for hash 5af6035667cccf2a40134bec6feb42dabc024cbdef61aa008aaf53c8e29b7406 corresponding to nodeKey nZg@KBڼL

goroutine 1 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/iavl.(*nodeDB).GetNode(0xc0000c6b90, 0xc0008b3e40, 0x20, 0x20, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/iavl/nodedb.go:82 +0x617
github.com/binance-chain/node/vendor/github.com/tendermint/iavl.(*Node).getRightNode(...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/iavl/node.go:363
github.com/binance-chain/node/vendor/github.com/tendermint/iavl.(*Node).get(0xc0000cfce0, 0xc000c820e0, 0x202a740, 0x13, 0x13, 0x1c, 0x1, 0x1507d40, 0xc000a28aa8)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/iavl/node.go:176 +0x319
github.com/binance-chain/node/vendor/github.com/tendermint/iavl.(*Node).get(0xc0000cf290, 0xc000c820e0, 0x202a740, 0x13, 0x13, 0x8, 0xc000032fc0, 0xc000a604e0, 0xc000a28aa8)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/iavl/node.go:177 +0x293
github.com/binance-chain/node/vendor/github.com/tendermint/iavl.(*ImmutableTree).Get(...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/iavl/immutable_tree.go:98
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/store.(*IavlStore).Get(0xc000c821c0, 0x202a740, 0x13, 0x13, 0x2090180, 0xc0008a2d00, 0x1507d40)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/store/iavlstore.go:153 +0x86
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/store.(*cacheKVStore).Get(0xc000a78d40, 0x202a740, 0x13, 0x13, 0x0, 0x0, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/store/cachekvstore.go:50 +0x125
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/x/auth.AccountKeeper.GetNextAccountNumber(0x14e86c0, 0xc0008a2d10, 0x136fe68, 0xc0008ef7a0, 0x14f7580, 0xc000a60990, 0xc000c88280, 0xb, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/x/auth/mapper.go:162 +0xc9
github.com/binance-chain/node/app.(*BinanceChain).initChainerFn.func1(0x14f7580, 0xc000a60990, 0xc000c88280, 0xb, 0x1ddb536b, 0xed4127047, 0x0, 0xc00037ec20, 0x12, 0xc000c88140, ...)
        /home/suyu/go/src/github.com/binance-chain/node/app/app.go:340 +0x350
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000c3e690, 0x1ddb536b, 0xed4127047, 0x0, 0xc00037ec20, 0x12, 0xc000c88140, 0x208e8b8, 0x0, 0x0, ...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:352 +0x19f
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/concurrent.(*asyncLocalClient).InitChainSync(0xc0000cfb80, 0x1ddb536b, 0xed4127047, 0x0, 0xc00037ec20, 0x12, 0xc000c88140, 0x208e8b8, 0x0, 0x0, ...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/concurrent/async_local_client.go:397 +0xec
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc00094f980, 0x1ddb536b, 0xed4127047, 0x0, 0xc00037ec20, 0x12, 0xc000c88140, 0x208e8b8, 0x0, 0x0, ...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:103 +0x6b
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000b9c300, 0xa, 0x0, 0xc00048af40, 0x6, 0xc00037ed20, 0x12, 0x232f675, 0x245e59d, 0xc00037ed40, ...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:307 +0x68f
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000b9c300, 0x150ce00, 0xc0008efa40, 0x2, 0x14f8140)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:266 +0x6fa
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node.NewNode(0xc000942840, 0x14f8300, 0xc000b54780, 0xc000a7a130, 0x14d80e0, 0xc000c02230, 0xc000a7a3b0, 0x1371860, 0xc000a7a3c0, 0x14f8140, ...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node/node.go:295 +0xe64
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000890fc0, 0x1372110, 0x1d, 0x0, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:133 +0x561
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000c4e480, 0xc0008912e0, 0x0, 0x2, 0x0, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:44 +0xb5
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc000c4e480, 0xc0008912a0, 0x2, 0x2, 0xc000c4e480, 0xc0008912a0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000900d80, 0x2, 0xc000891200, 0x1216e16)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000900d80, 0x1372518, 0x2, 0xc000bbfe50)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
        /home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef

**Comment by chaonan1992** [comment]
How to deal with it

**Comment by huangsuyu** [comment]
@chaonan1992 hello,

can you provide more info about this error?

was it on testnet or mainnet?
which version did you run?
did you enable state-sync?
