### ISSUE TITLE
Problem starting node ( testnet version 0.6.1)

### ISSUE THREAD

**Issue by Richzendy** [binance-chain/node-binary#109]
I getting this error starting the node, some tries before was working fine, but now always i get this error and the node don't start.

the config/priv_validator_state.json and data folder was removed but still the error persists.

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/binance-chain/node/plugins/dex/order.(*Keeper).LoadOrderBookSnapshot(0xc0008f6820, 0x14f7580, 0xc000c29260, 0xc0008bfe80, 0xb, 0x0, 0x32e18e49, 0xed4ff0736, 0x0, 0x0, ...)
        /home/suyu/go/src/github.com/binance-chain/node/plugins/dex/order/keeper_recovery.go:168 +0x1070
github.com/binance-chain/node/plugins/dex/order.(*Keeper).initOrderBook(0xc0008f6820, 0x14f7580, 0xc000c29260, 0xc0008bfe80, 0xb, 0x0, 0x7, 0xc000b9c7a8, 0x150b240, 0xc0000b42f8, ...)
        /home/suyu/go/src/github.com/binance-chain/node/plugins/dex/order/keeper_recovery.go:279 +0xce
github.com/binance-chain/node/plugins/dex/order.(*Keeper).Init(0xc0008f6820, 0x14f7580, 0xc000c29260, 0xc0008bfe80, 0xb, 0x0, 0x7, 0xc000b9c7a8, 0x150b240, 0xc0000b42f8, ...)
        /home/suyu/go/src/github.com/binance-chain/node/plugins/dex/order/keeper.go:94 +0xbb
github.com/binance-chain/node/app.(*BinanceChain).initDex(0xc0004ae500, 0x1504ca0, 0xc00095c600)
        /home/suyu/go/src/github.com/binance-chain/node/app/app.go:292 +0x309
github.com/binance-chain/node/app.NewBinanceChain(0x14f8140, 0xc000c2efe0, 0x150b240, 0xc0000b4470, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100)
        /home/suyu/go/src/github.com/binance-chain/node/app/app.go:233 +0x19d3
main.newApp(0x14f8140, 0xc000c2efe0, 0x150b240, 0xc0000b4470, 0x0, 0x0, 0xc000c72000, 0xc000b9d978)
        /home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:23 +0x78
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000164ee0, 0x1372110, 0x1d, 0x0, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:117 +0x184
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc0009ea480, 0xc000165240, 0x0, 0x2, 0x0, 0x0)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:44 +0xb5
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc0009ea480, 0xc000165200, 0x2, 0x2, 0xc0009ea480, 0xc000165200)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0009e2d80, 0x2, 0xc000165160, 0x1216e16)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0009e2d80, 0x1372518, 0x2, 0xc000a93d80)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
        /home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef
```

**Comment by huangsuyu** [comment]
hello, @Richzendy 

This issue should be fixed in this new release: https://github.com/binance-chain/node-binary/pull/110

Please have a try, thanks so much!

**Comment by Richzendy** [comment]
Hi! trying the binaries on the new folder ( 0.6.1-hotfix ) i had this error:

```
panic: ERROR:
Codespace: 5
Code: 9
Message: "Initial ProposalID already set"


goroutine 1 [running]:
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/x/gov.InitGenesis(0x1463620, 0xc000afd8f0, 0xc002ad66c0, 0xb, 0xc00017c9a0, 0x1454820, 0xc00001ab60, 0x1454860, 0xc00001aba0, 0xc00030daa0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/x/gov/genesis.go:49 +0x35c
github.com/binance-chain/node/app.(*BinanceChain).initChainerFn.func1(0x1463620, 0xc000afd8f0, 0xc002ad66c0, 0xb, 0x1ddb536b, 0xed4127047, 0x0, 0xc0029f5680, 0x12, 0xc002ad6580, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/app/app.go:352 +0x7b2
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000bcea50, 0x1ddb536b, 0xed4127047, 0x0, 0xc0029f5680, 0x12, 0xc002ad6580, 0x1de15b0, 0x0, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:352 +0x19f
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/concurrent.(*asyncLocalClient).InitChainSync(0xc002944fd0, 0x1ddb536b, 0xed4127047, 0x0, 0xc0029f5680, 0x12, 0xc002ad6580, 0x1de15b0, 0x0, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/concurrent/async_local_client.go:397 +0xec
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc002abe340, 0x1ddb536b, 0xed4127047, 0x0, 0xc0029f5680, 0x12, 0xc002ad6580, 0x1de15b0, 0x0, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:103 +0x6b
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc002aced80, 0xa, 0x0, 0xc0041a3806, 0x6, 0xc0029f5740, 0x12, 0x23d7173, 0x2467239, 0xc0029f5760, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:307 +0x68f
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc002aced80, 0x1478f00, 0xc003e08a10, 0x2, 0x14641e0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:266 +0x6fa
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node.NewNode(0xc0000b89a0, 0x14643a0, 0xc002a2a960, 0xc00293aa50, 0x1444420, 0xc0028c65a0, 0xc00293acd0, 0x12de080, 0xc00293ace0, 0x14641e0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node/node.go:295 +0xe64
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00015bd40, 0x12de930, 0x1d, 0x0, 0x0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:133 +0x561
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000bf6fc0, 0xc00000d1c0, 0x0, 0x2, 0x0, 0x0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:44 +0xb5
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc000bf6fc0, 0xc00000ccc0, 0x2, 0x2, 0xc000bf6fc0, 0xc00000ccc0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c58c0, 0x2, 0xc00000c320, 0x11835eb)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000c58c0, 0x12ded38, 0x2, 0xc000bae400)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
        /Users/huangsuyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef
```

After remove data folder and  config/priv_validator_state.json file the process from linux/bnbchaind runs fine some minutes and die with the last error.

**Comment by liketux** [comment]
I get the same error in testnet (0.6.1-hotfix)

`./bnbchaind start --home ./.bnbchaind
panic: ERROR:
Codespace: 5
Code: 9
Message: "Initial ProposalID already set"


goroutine 1 [running]:
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/x/gov.InitGenesis(0x1463620, 0xc001e6d1d0, 0xc002b733c0, 0xb, 0xc0008f2770, 0x1454820, 0xc0008f8200, 0x1454860, 0xc0008f8240, 0xc000c74960, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/x/gov/genesis.go:49 +0x35c
github.com/binance-chain/node/app.(*BinanceChain).initChainerFn.func1(0x1463620, 0xc001e6d1d0, 0xc002b733c0, 0xb, 0x1ddb536b, 0xed4127047, 0x0, 0xc01a939be0, 0x12, 0xc002b73280, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/app/app.go:352 +0x7b2
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0003512c0, 0x1ddb536b, 0xed4127047, 0x0, 0xc01a939be0, 0x12, 0xc002b73280, 0x1de15b0, 0x0, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/baseapp/baseapp.go:352 +0x19f
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/concurrent.(*asyncLocalClient).InitChainSync(0xc003caa4d0, 0x1ddb536b, 0xed4127047, 0x0, 0xc01a939be0, 0x12, 0xc002b73280, 0x1de15b0, 0x0, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/concurrent/async_local_client.go:397 +0xec
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc002d158c0, 0x1ddb536b, 0xed4127047, 0x0, 0xc01a939be0, 0x12, 0xc002b73280, 0x1de15b0, 0x0, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:103 +0x6b
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc01be62900, 0xa, 0x0, 0xc01a94d8c0, 0x6, 0xc01a939ca0, 0x12, 0x24c28f7, 0x24a67e2, 0xc01a939cc0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:307 +0x68f
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01be62900, 0x1478f00, 0xc0032c7dc0, 0x2, 0x14641e0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:266 +0x6fa
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node.NewNode(0xc0000969a0, 0x14643a0, 0xc01b164dc0, 0xc00481d8b0, 0x1444420, 0xc0000a1ae0, 0xc00481dba0, 0x12de080, 0xc00481dbb0, 0x14641e0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node/node.go:295 +0xe64
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00032e2c0, 0x12de930, 0x1d, 0x0, 0x0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:133 +0x561
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000084480, 0xc00032e620, 0x0, 0x2, 0x0, 0x0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:44 +0xb5
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc000084480, 0xc00032e5e0, 0x2, 0x2, 0xc000084480, 0xc00032e5e0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000334d80, 0x2, 0xc00032e540, 0x11835eb)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000334d80, 0x12ded38, 0x2, 0xc000038e80)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
        /Users/huangsuyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef
`

**Comment by Richzendy** [comment]
It's working now with v0.6.2 after remove config/priv_validator_state.json and data folder.

Thanks a lot!
