### ISSUE TITLE
Any example of Failed Transfer  transaction on binance chain?

### ISSUE THREAD

**Issue by bitrocks** [binance-chain/node-binary#112]
I can't find any example of failed transfer transaction.

**Comment by huangsuyu** [comment]
Not sure about transfer transaction, but there is one for `cancel`: https://explorer.binance.org/tx/F296E84917A92FC4876AFE77DE662CC9417F9D6F2EB8ED1AD723A5433EBB8362

**Comment by hughsvision** [comment]
> Not sure about transfer transaction, but there is one for `cancel`: https://explorer.binance.org/tx/F296E84917A92FC4876AFE77DE662CC9417F9D6F2EB8ED1AD723A5433EBB8362

Thanks. I've found non-transfer type failed transaction before, but not see any failed transfer type tx.

**Comment by astudnev** [comment]
Number of failed TX by type till now are:
┌─tx_type──────┬─count()─┐
│ NEW_ORDER    │       2 │
│ CANCEL_ORDER │    2550 │
└──────────────┴─────────┘
