### ISSUE TITLE
How to index already synced data?

### ISSUE THREAD

**Issue by dingyo777** [binance-chain/node-binary#116]
I've run mainnet of binance.

I found out that I should set `tx.height` to `index_tags` on `config.toml`.

The problem is I found out this configuration too later, that is, after all the block has been synced.

When I restarted bnb again after modifying `config.toml`, newly synced transactions are indexed well but already synced transactions are not indexed.

Do you know how to index already synced transaction, too?

**Comment by huangsuyu** [comment]
Hello, @dingyo777 
I'm afraid you cannot add index back.

**Comment by dingyo777** [comment]
@huangsuyu
Thank you for your confirmation.
