### ISSUE TITLE
how to get account balance using ABCI rpc api on binance full node?

### ISSUE THREAD

**Issue by dingyo777** [binance-chain/node-binary#117]
# I want to get balance of any account using rpc ABCI api on binance full node.

For that, I'm referring to https://docs.binance.org/api-reference/node-rpc.html#619-abciquery.

But when I tested the RPC API with the example on the shared example, it doesn't return value field.

My test curl and its result is 
```
user:~/.bnbchaind/config$ curl 'localhost:27147/abci_query?path="/store/acc/key"&data=0x6163636F756E743A89F856CB39D25C1BDDAAEC74A381577CA8E2F886'
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "response": {
      "key": "YWNjb3VudDqJ+FbLOdJcG92q7HSjgVd8qOL4hg==",
      "height": "35050367"
    }
  }
}
```

I guess the data part `0x6163636F756E743A89F856CB39D25C1BDDAAEC74A381577CA8E2F886` is a little bit unclear. 

How create this data part???

Especially, according to doc,
```
“account:” in ASCII is 6163636F756E756E and the address derived from public key is 
743A89F856CB39D25C1BDDAAEC74A381577CA8E2F886. You need to add these to part to get the 
correct key.
```
Here, what does `the address derived from public key` mean?

**Comment by huangsuyu** [comment]
@dingyo777 
the hex address is decoded from a bech32 encoded address. https://docs.binance.org/blockchain.html#address 

There is a function for decoding: https://github.com/binance-chain/javascript-sdk/wiki/API-Documentation#module_crypto.decodeAddress

**Comment by dingyo777** [comment]
@huangsuyu 
Thank you for the confirmation.
May I get the python version of decoding method?
Is it same one?
https://github.com/sammchardy/python-binance-chain/blob/866f191007acbd40c4e8586df9ac3cb66253b863/binance_chain/utils/segwit_addr.py#L113

**Comment by dingyo777** [comment]
Self response.

Yep, we can use this one: https://github.com/sammchardy/python-binance-chain/blob/866f191007acbd40c4e8586df9ac3cb66253b863/binance_chain/utils/segwit_addr.py#L113

**Comment by freddieee** [comment]
Hi @dingyo777, in this case, how did you get `743A89F856CB39D25C1BDDAAEC74A381577CA8E2F886` from the public key or bech32 format address? I could only get `813e4939f1567b219704ffc2ad4df58bde010879` with the function you mentioned

**Comment by dingyo777** [comment]
@freddieee 
Hello :)
It is easy if you get hex address from bech32 format address.

Recently I added some sample codes in my github.
I hope that it can be helpful to you.

https://github.com/dingyo777/binance_chain_python_sample/blob/master/examples/decode_tx.py#L28

And additionally, if you get account info using ABCI query, please refer to https://github.com/dingyo777/binance_chain_python_sample/blob/master/examples/decode_tx.py#L32
and 
https://docs.binance.org/api-reference/node-rpc.html#619-abciquery

**Comment by freddieee** [comment]
@dingyo777 Thank you so much! It saves a lot of time.
