### ISSUE TITLE
python code for decoding ABCI query result

### ISSUE THREAD

**Issue by dingyo777** [binance-chain/node-binary#119]
With a help from @huangsuyu, I can query account info like below
```
dingyo  ~/Projects/python3_test : curl 'https://dataseed5.defibit.io/abci_query?path="/store/acc/key"&data=0x6163636F756E743A17DE0C01355DDF0B4380A34ACBFA2C701A5905A7'

{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "response": {
      "key": "YWNjb3VudDoX3gwBNV3fC0OAo0rL+ixwGlkFpw==",
      "value": "S9xMJwqCAQoUF94MATVd3wtDgKNKy/oscBpZBacSCgoDQk5CEPrv5QYSDgoHRUNPLTA4MxCAwtcvEg8KB1BWVC01NTQQ8cn7/wESDgoHU0xWLTk4NhCAwtcvGibrWumHIQP6sPFgBhRC5LaiNTVw7GCvbDKetU91BJVo4EwZJhMlqiCurQYogwI=",
      "height": "35239343"
    }
  }
}
```

I failed to test this curl on my own full node. 
```
ubuntu@test:~/.bnbchaind/config$ curl 'localhost:27147/abci_query?path="/store/acc/key"&data=0x6163636F756E743A17DE0C01355DDF0B4380A34ACBFA2C701A5905A7'

{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "response": {
      "key": "YWNjb3VudDoX3gwBNV3fC0OAo0rL+ixwGlkFpw==",
      "height": "1745286"
    }
  }
}
```

When I tested same curl on my own node, it doesn't return value field as response but I guess it's because my own node is not synced yet fully.

---

# How to decode value field of ABCI query result?

For example, as above response is, there is encoded value field like
```
"value": "S9xMJwqCAQoUF94MATVd3wtDgKNKy/oscBpZBacSCgoDQk5CEPrv5QYSDgoHRUNPLTA4MxCAwtcvEg8KB1BWVC01NTQQ8cn7/wESDgoHU0xWLTk4NhCAwtcvGibrWumHIQP6sPFgBhRC5LaiNTVw7GCvbDKetU91BJVo4EwZJhMlqiCurQYogwI="
```

Since it's a little bit hard for me to decode the result, if there is a sample python code, it would be really helpful to me.

---
It seems that I can do something from this file :
https://github.com/binance-chain/java-sdk/blob/483a21e23800ef718bea6d0800fcce212add3b18/src/main/proto/dex.proto

There is `AppAccount` like
```
message AppAccount {
    //    uint64 SIZE-OF-ENCODED // varint encoded length of the structure after encoding
    //    0x4BDC4C27   // hardcoded, object type prefix in 4 bytes
    message baseAccount {
        bytes address = 1;
        repeated Token coins = 2;
        bytes public_key = 3;
        int64 account_number = 4;
        int64 sequence = 5;
    }
    baseAccount base = 1;
    string name = 2;
    repeated Token frozen = 3;
    repeated Token locked = 4;
}
```

It may be helpful.

Let me try.

**Comment by dingyo777** [comment]
It seems that I can do something from this file :
https://github.com/binance-chain/java-sdk/blob/483a21e23800ef718bea6d0800fcce212add3b18/src/main/proto/dex.proto

There is `AppAccount` like
```
message AppAccount {
    //    uint64 SIZE-OF-ENCODED // varint encoded length of the structure after encoding
    //    0x4BDC4C27   // hardcoded, object type prefix in 4 bytes
    message baseAccount {
        bytes address = 1;
        repeated Token coins = 2;
        bytes public_key = 3;
        int64 account_number = 4;
        int64 sequence = 5;
    }
    baseAccount base = 1;
    string name = 2;
    repeated Token frozen = 3;
    repeated Token locked = 4;
}
```

It may be helpful.

Let me try.

**Comment by huangsuyu** [comment]
Hello， @dingyo777 

There is an example in go-sdk: https://github.com/binance-chain/go-sdk/blob/7eb811572b167edacbf1b92da81937c1a46c10d5/client/rpc/dex_client.go#L143

**Comment by dingyo777** [comment]
Hello @huangsuyu 
Thank you for your advice.

Finally I resolved.
Please refer to my github code if you has interests:
https://github.com/dingyo777/binance_chain_python_sample/blob/master/examples/decode_tx.py#L36
