### ISSUE TITLE
How to query all transactions in a time range using public API

### ISSUE THREAD

**Issue by YordanPavlov** [binance-chain/node-binary#120]
What would be the correct API endpoint to query for all transactions within a time range. What I have tried is:

` curl "https://dex.binance.org/api/v1/transactions?startTime=1565683885966&endTime=1565684785966&rows=3&page=11"`

but that does seem to require an address specified.

**Comment by huangsuyu** [comment]
hello, @YordanPavlov 

You can use this function to query all the transactions within certain heights: https://docs.binance.org/api-reference/dex-api/paths.html#apiv2transactions-in-blockblockheight

**Comment by YordanPavlov** [comment]
Thanks for your reply @huangsuyu 
just to be clear, if I want to get all the transactions in the range of block number 1M and 2M, the way to do it is to make 1M requests using the API point you provided.

**Comment by huangsuyu** [comment]
@YordanPavlov 

If you have your own node running with `fast-sync` and enable range query: `enable_range_query = true` and `index_tags=tx.height`
https://github.com/binance-chain/node-binary/blob/master/fullnode/prod/0.6.3-hotfix/config/config.toml#L358 

You can query  all the transactions in the range of block number 1M and 2M like this:
`curl http://localhost:27147/tx_search?query=%22tx.height%3E1000000%20AND%20tx.height%3C2000000%22`

**Comment by huangsuyu** [comment]
Close this for now, please reopen when necessary.
