### ISSUE TITLE
Can not to run fullnode(Mac OS)

### ISSUE THREAD

**Issue by BananaLF** [binance-chain/node-binary#122]
I use **bnbchaind** and **bnbcli**(0.6.1 mac) to run fullnode. then I get some error.

> ./mac/bnbchaind: line 1: version: command not found
>
> ./mac/bnbchaind: line 2: oid: command not found
>
>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/size: 44221732 No such file or directory

**Comment by huangsuyu** [comment]
hello, @BananaLF 

Please use `wget` to download the binary, it's stored with `git lfs`
