### ISSUE TITLE
ABCInfo query to Node RPC ignores height parameter

### ISSUE THREAD

**Issue by astudnev** [binance-chain/node-binary#125]
Documentation claims that height parameter is accepted: https://docs.binance.org/api-reference/node-rpc.html#611-query-abciinfo

However is i query the fees for the latest block and the block before fees were changed, they appears the same:

For latest:
https://dataseed1.ninicoin.io/abci_query?path=%22/param/fees%22&height=0

For the old block:
https://dataseed1.ninicoin.io/abci_query?path=%22/param/fees%22&height=100

Same result.

**Comment by huangsuyu** [comment]
Hello, @astudnev 

Since the fees are fixed on Binance Chain, fee parameters doesnt need height parameter. You can see the sdk function here: https://github.com/binance-chain/go-sdk/blob/7eb811572b167edacbf1b92da81937c1a46c10d5/client/rpc/dex_client.go#L217

**Comment by astudnev** [comment]
Historically this is not true. They were changed at least once, on 13 of June

**Comment by huangsuyu** [comment]
@astudnev 

The abci query only queries the latest height and you cannot set the height. 

It's true that fees were changed by on-chain proposals. You can search for the proposals for details.

**Comment by astudnev** [comment]
> @astudnev
> 
> The abci query only queries the latest height and you cannot set the height.
> 
> It's true that fees were changed by on-chain proposals. You can search for the proposals for details.

The documentation then confusing, it says i can put height parameter in any ABCInfo query and i expect that it works for all types of queries

**Comment by HaoyangLiu** [comment]
> The documentation then confusing, it says i can put height parameter in any ABCInfo query and i expect that it works for all types of queries

Only in the key-value store query, you can put height parameter. However, the fee query command is not implemented in that way. Besides, a full node only supports key-value query in latest 10000 height. And transaction fee won't be changed frequently. So it is very likely that you can't get any fee changes in latest 10000 height.
