### ISSUE TITLE
How can you know what height ( > 0) to set for state_sync_height

### ISSUE THREAD

**Issue by razvan-bugheanu-sftle** [binance-chain/node-binary#126]
Hi,
I am trying to use state_sync from a given height. The issue is it starts from height 0 even if I tried with different state_sync_height values (e.g. 35000000).

From what I have read on BEP18, it says somewhere that the configured height must match some peer's snapshot height, but I don't know how to find out some peers available snapshots heights information.

Can you provide a working example (I am trying on mainnet, I have version 0.6.1) ?

This is very important for someone who needs to synch from a historical block. but not from genesis.

**Comment by huangsuyu** [comment]
Hello, @razvan-bugheanu-sftle 

The latest snapshot height is 40242473.

When do you wish to sync from?  You can find the snapshot height from explorer. the are the first block after 0:00 UTC.

**Comment by razvan-bugheanu-sftle** [comment]
That is great, thank you.
