### ISSUE TITLE
too many open files error

### ISSUE THREAD

**Issue by ArseniiPetrovich** [binance-chain/node-binary#128]
I have started two BNB nodes with the pretty same configuration as described at your docs. Some time later both of them became irresponsive. Systemd logs showed me a bunch of `too many open files` errors.
Restart helps for a time, but it is not a permanent solution. Could you help me dig into it, please?

**Comment by huangsuyu** [comment]
Hello, @ArseniiPetrovich 

Please take a look at this: https://docs.binance.org/fullnodeissue.html#bnbchaind-crashes-because-of-too-many-open-files

You need to change the configuration of your server.

**Comment by ArseniiPetrovich** [comment]
Thanks!

**Comment by ArseniiPetrovich** [comment]
Hello again, @huangsuyu. Sorry to bother you, but this solution doesn't seem to be working anymore. I still ran into this issue with modified open files limit (65535)

**Comment by ArseniiPetrovich** [comment]
That's pretty strange but even a node reboot didn't help.

**Comment by ArseniiPetrovich** [comment]
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30357
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Version: 0.6.2

**Comment by ArseniiPetrovich** [comment]
Upgraded to 0.6.3. The same error.

**Comment by ArseniiPetrovich** [comment]
Closed as after the update another issue appeared. See #164 for details.

**Comment by ArseniiPetrovich** [comment]
Have to open this issue once again.
After fixing #163 this issue appeared again: `panic: open /home/ec2-user/.bnbchaind/data/application.db/5765962.ldb: too many open files`
`ulimit -a`:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30357
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
I tried to increase file limit 10 times, but error still persist.

**Comment by ArseniiPetrovich** [comment]
@huangsuyu 
Can you look into it, please?

**Comment by huangsuyu** [comment]
> @huangsuyu
> Can you look into it, please?

Can you bump your node version and try again? v0.6.3 should fix this

**Comment by huangsuyu** [comment]
> @huangsuyu
> Can you look into it, please?

Can you bump your node version and try again? v0.6.3 should fix this

**Comment by ArseniiPetrovich** [comment]
Seems that 0.6.3 fixed this indeed.
