### ISSUE TITLE
Error after updating to 0.6.2

### ISSUE THREAD

**Issue by APshenkin** [binance-chain/node-binary#133]
Node crashes after updating to 0.6.2

```
E[2019-10-14|14:30:27.693] Dialing failed                               module=pex addr=4594a86937dc96b0afcb1d16cf14dd5783e3724f@3.82.70.135:27146 err="dial tcp 3.82.70.135:27146: connect: connection refused" attempts=0
E[2019-10-14|14:30:27.767] Connection failed @ recvRoutine (reading byte) module=p2p peer=b323708b0bd429a95154ff0a287f0f42f432cb62@34.247.169.233:27146 conn=MConn{34.247.169.233:27146} err=EOF
E[2019-10-14|14:30:27.767] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
panic: Failed to process committed block (41277001:95A3A187E43C431C3205C0B81891E075C647988D38D9E6F2E4E30E00A63CDDDE): Wrong Block.Header.AppHash.  Expected 877BD40C8068863FB000EDC917A0E2C3B38F14F86F610129F6946344AB061F94, got 588061D18993C67A8D4070C564097636895090B8832BE87455D70B13D377933D
goroutine 213102 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0048321a0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:400 +0x18cc
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:125 +0x84
Running /usr/local/bin/entrypoint.sh in /


ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 877BD40C8068863FB000EDC917A0E2C3B38F14F86F610129F6946344AB061F94, got 588061D18993C67A8D4070C564097636895090B8832BE87455D70B13D377933D
```

**Comment by astudnev** [comment]
I have exactly same error now

**Comment by astudnev** [comment]
Please note very important that if you upgrading AFTER the error, you should do recover: 
```
./state_recover 41276999 /home/studnev/.bnbchaind
recover home_path[/home/studnev/.bnbchaind] to height[41276999]
recover success
```

**Comment by Alteryy** [comment]
after state_recover 41276999
error log:
 panic: Failed to process committed block (41277001:95A3A187E43C431C3205C0B81891E075C647988D38D9E6F2E4E30E00A63CDDDE): Wrong Block.Header.AppHash.  Expected 877BD40C8068863FB000EDC917A0E2C3B38F14F86F610129F6946344AB061F94, got 588061D18993C67A8D4070C564097636895090B8832BE87455D70B13D377933D

goroutine 213123 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc00afbf380)
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:372 +0x1874
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /home/suyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x84

I[2019-10-15|02:19:12.280] added a peer to state sync reactor           module=statesync peer=48dada912ff10f04dec0db7900a78750384d06fd
I[2019-10-15|02:19:12.282] added a peer to state sync reactor           module=statesync peer=b323708b0bd429a95154ff0a287f0f42f432cb62
E[2019-10-15|02:19:12.418] Dialing failed                               module=pex addr=1ebb7d9bc3ee3001f41200ed4f4be5432586c43e@34.92.4.164:27147 err="dial tcp 34.92.4.164:27147: i/o timeout" attempts=0
E[2019-10-15|02:19:12.555] Connection failed @ recvRoutine (reading byte) module=p2p peer=b323708b0bd429a95154ff0a287f0f42f432cb62@34.247.169.233:27146 conn=MConn{34.247.169.233:27146} err=EOF
E[2019-10-15|02:19:12.555] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
I[2019-10-15|02:19:12.558] No new orders for any pair, give up matching module=dexkeeper 
I[2019-10-15|02:19:12.558] No order comes in for the block              module=dexkeeper 
I[2019-10-15|02:19:12.563] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
I[2019-10-15|02:19:12.564] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
I[2019-10-15|02:19:12.571] start to collect publish information         module=pub height=41277000
I[2019-10-15|02:19:12.572] start to publish                             module=pub height=41277000 blockTime=1571059218733773104 numOfTrades=0 numOfOrders=0 numOfProposals=0 numOfStakeUpdates=0 numOfAccounts=0
E[2019-10-15|02:19:12.698] Dialing failed                               module=pex addr=bb721fe089e83d42bcb8f629f8efe0e4af888fde@52.197.88.253:27146 err="auth failure: conn.ID (98579505572cc85488caa403bebb62e5b61d68e0) dialed ID (bb721fe089e83d42bcb8f629f8efe0e4af888fde) mismatch" attempts=0

**Comment by crcrcr999** [comment]
Add 
BEP3Height = 41277000
to app.toml or copy prod/config/app.toml to your bnbchind/config  path and then recovery to 41276999 by state_recover.
I think maybe should add a note on release page,cost me about 2 hours.

**Comment by APshenkin** [comment]
Thank you for solution
