### ISSUE TITLE
update to 0.6.2 has an error

### ISSUE THREAD

**Issue by ruanqunfeng** [binance-chain/node-binary#134]
failed to get rootMultiStore: no data

![image](https://user-images.githubusercontent.com/15098545/66794353-cd679900-ef33-11e9-9582-2377aab5683f.png)

**Comment by yutianwu** [comment]
can you provide more detailed information

**Comment by yutianwu** [comment]
or you can refer to: https://github.com/binance-chain/node-binary/issues/133

**Comment by ruanqunfeng** [comment]
Thank you, this problem has been solved.
