### ISSUE TITLE
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.

### ISSUE THREAD

**Issue by dingyo777** [binance-chain/node-binary#135]
I don't know where I should post this kind of question.
If there is more proper online space, please let me know.

I stopped my binance full node and when I restart again, I got below error
```
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 877BD40C8068863FB000EDC917A0E2C3B38F14F86F610129F6946344AB061F94, got 588061D18993C67A8D4070C564097636895090B8832BE87455D70B13D377933D
```

I've run binance full node on linux ubuntu 18.04 with 0.6.1 version.

I tried with new version 0.6.2, but it doesn't resolve my issue. Is there anybody know who handles this problem??

**Comment by huangsuyu** [comment]
Hello, @dingyo777 
It seems that you forgot to upgrade your node before height **41,277,000**

Please follow this guide to recover to 41,276,999: https://docs.binance.org/fullnodeissue.html#forget-to-upgrade

**Comment by dingyo777** [comment]
@huangsuyu 
You are my savior~!
Thank you so much~!
Let me try~!!

**Comment by huangsuyu** [comment]
cool, will close this!

**Comment by dingyo777** [comment]
@huangsuyu 
It works well~!
Thank you again~!!
