### ISSUE TITLE
Multiple test tokens Faucet retreivel

### ISSUE THREAD

**Issue by JurgenSchouppe** [binance-chain/node-binary#139]
Hello,

How can i receive multiple test tokens (BNB) on the same wallet address?

{"codespace":1,"code":5,"abci_code":65541,"message":"insufficient fund. you got 20000000000BNB, but 50000000000BNB fee needed."}

**Comment by huangsuyu** [comment]
Hello, @JurgenSchouppe 
where did you get testnet token?
