### ISSUE TITLE
problem of bnbcli

### ISSUE THREAD

**Issue by jakilwq** [binance-chain/node-binary#140]
i execute "./bnbcli api-server --laddr tcp://0.0.0.0:8080 --node tcp://127.0.0.1:27147 --trust-node"  and get error:

panic: leveldb/storage: storage is read-only

goroutine 1 [running]:
github.com/binance-chain/node/plugins/api.newServer(0xc0008c70a0, 0xc000c89520, 0x12242c0, 0xc000caa7e0, 0x11f0a20, 0xc00000e018, 0x0, 0x7ffd15472743, 0x15, 0x0, ...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/plugins/api/server.go:39 +0x28b
github.com/binance-chain/node/plugins/api.ServeCommand.func1(0xc000c618c0, 0xc0008a7360, 0x0, 0x5, 0x0, 0x0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/plugins/api/cli.go:34 +0x1b3
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc000c618c0, 0xc0008a7310, 0x5, 0x5, 0xc000c618c0, 0xc0008a7310)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a11de0, 0xc41f3f, 0x1a11de0, 0xf513af)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1a11de0, 0x10c99e8, 0x2, 0xc000c3c240)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
        /Users/huangsuyu/go/src/github.com/binance-chain/node/cmd/bnbcli/main.go:105 +0x8de

**Comment by huangsuyu** [comment]
Hello, @jakilwq 

Please read the doc here: https://docs.binance.org/api-reference/api-server.html

it seems you miss `--chain-id` parameter

**Comment by HaoyangLiu** [comment]
@jakilwq 
It seems that the default home directory(`$HOME/.bnbcli`) is read only, maybe you should specify a new home directory for bnbcli:
`./bnbcli api-server --laddr tcp://0.0.0.0:8080 --node tcp://127.0.0.1:27147 --trust-node --home {new directory}`
