### ISSUE TITLE
Get not found error when using bnbcli

### ISSUE THREAD

**Issue by cbarraford** [binance-chain/node-binary#141]
Within a `golang:alpine` docker image, i can't seem to run `bnbcli`. I get the following error. Any help would be great, thanks!!

```
/binance/cli/prod/0.6.2/linux # ./bnbcli
./bnbcli: line 1: version: not found
./bnbcli: line 2: oid: not found
./bnbcli: line 3: size: not found
```

**Comment by HaoyangLiu** [comment]
Please refer to https://github.com/git-lfs/git-lfs/wiki/Installation
