### ISSUE TITLE
How can I make the HTTP API accessible to my local full node? 

### ISSUE THREAD

**Issue by wshhz** [binance-chain/node-binary#142]
How can I make the HTTP API accessible to my local full node? Because the interfaces provided by Node RPC and API Server are not enough.

**Comment by huangsuyu** [comment]
@wshhz 

I'm afraid that you cannot use HTTP API from your own full node. Those services are only provided by [accelerated nodes](https://docs.binance.org/faq.html#what-is-the-accelerated-node)

**Comment by wshhz** [comment]
Can I run an acceleration node locally?

**Comment by wshhz** [comment]
So can I access my own nodes only through NODE RPC and API Server?

**Comment by huangsuyu** [comment]
@wshhz yes, you can

**Comment by wshhz** [comment]
Why not provide the public API of the local node?
