### ISSUE TITLE
About Enable Indexer

### ISSUE THREAD

**Issue by mutianqi** [binance-chain/node-binary#143]
I have enable Indexer,but search tx.height is null

config：
![image](https://user-images.githubusercontent.com/38172771/67650372-b4b9a300-f977-11e9-9543-d6c117a109ae.png)

![image](https://user-images.githubusercontent.com/38172771/67650241-365d0100-f977-11e9-9beb-f1db36759389.png)

**Comment by huangsuyu** [comment]
hello, @mutianqi 

please read https://docs.binance.org/api-reference/node-rpc.html#6115-query-txsearch about how to add indexer.

**Comment by mutianqi** [comment]
[https://github.com/binance-chain/node-binary/issues/131](url)
modify the index_tags to tx.height or adding 'tx.height = ""'?
if I adding the 'tx.height = ""',emmm...
```
![image](https://user-images.githubusercontent.com/38172771/67659790-33263d00-f998-11e9-8318-490de4dc983a.png)
````

**Comment by huangsuyu** [comment]
Please put:
```
index_tags = "tx.hash,tx.heght"
```
