### ISSUE TITLE
Command Not Found Error: BNBCLI

### ISSUE THREAD

**Issue by MalayTripathi** [binance-chain/node-binary#154]
Hi Team,

I am getting the following error when trying to use BNBCLI on mac/linux.

System Details: MacBook Air
OS: macOS Catalina 10.15.1
Shell: zsh (Tried on bash too but same result)

Command Run: ./tbnbcli keys list

Output:

./tbnbcli: line 1: version: command not found
./tbnbcli: line 2: oid: command not found
__TEXT	__DATA	__OBJC	others	dec	hex
error: /Library/Developer/CommandLineTools/usr/bin/size: can't open file: 36728908 (No such file or directory)

Few days ago I had used the same command to issue a mintable asset on the Testnet but now I am getting this error when I recloned the repository and trying to create a listing proposal on the testnet for that asset.

**Comment by huangsuyu** [comment]
Hello, @MalayTripathi please use `wget` to download the whole `bnbcli` binary. it's currently stored with `git lfs`

**Comment by MalayTripathi** [comment]
Thank you @huangsuyu for the prompt reply. I tried to download it using wget but couldn't succeed. Also I tried using git-lfs to clone this repo but still couldn't get the complete repo. Then I downloaded the raw file needed and manually replaced the shell executable in the repo for that version.

I would be grateful if you can reply with the wget link reference to download the whole repository as intended.

Thank you.

**Comment by huangsuyu** [comment]
Hello, @MalayTripathi 

can you try this command?
```
 wget https://media.githubusercontent.com/media/binance-chain/node-binary/master/cli/prod/0.6.2/mac/bnbcli
```

**Comment by eltNEG** [comment]
> Hello, @MalayTripathi
> 
> can you try this command?
> 
> ```
>  wget https://media.githubusercontent.com/media/binance-chain/node-binary/master/cli/testnet/0.6.2/mac/tbnbcli
> ```

This works for me

**Comment by huangsuyu** [comment]
will close this one for now. Feel free to reopen it!

**Comment by MalayTripathi** [comment]
> Hello, @MalayTripathi
> 
> can you try this command?
> 
> ```
>  wget https://media.githubusercontent.com/media/binance-chain/node-binary/master/cli/testnet/0.6.2/mac/tbnbcli
> ```

It works. Although I cloned the repository first and then downloaded the executable file separately and replaced it with the one in cloned folder. It worked. Thanks for the help.
