### ISSUE TITLE
bnbcli txs failed

### ISSUE THREAD

**Issue by past2017** [binance-chain/node-binary#16]
As below, bnbcli txs failed, how to use bnbcli txs?
env: testne/0.5.8/linux
```
$ ~/node-binary/cli/testnet/linux/bnbcli  --chain-id=Binance-Chain-Nile txs  --tag test1,test2 --any
ERROR: TxSearch: Response error: RPC error -32603 - Internal error: 
parse error near PegText (line 1 symbol 2 - line 1 symbol 7):
"test1"
```

**Comment by huangsuyu** [comment]
> As below, bnbcli txs failed, how to use bnbcli txs?
> env: testne/0.5.8/linux
> 
> ```
> $ ~/node-binary/cli/testnet/linux/bnbcli  --chain-id=Binance-Chain-Nile txs  --tag test1,test2 --any
> ERROR: TxSearch: Response error: RPC error -32603 - Internal error: 
> parse error near PegText (line 1 symbol 2 - line 1 symbol 7):
> "test1"
> ```


There is not any existing tags added on transactions.
