### ISSUE TITLE
Upgrade to 0.6.3: failed to get rootMultiStore: no data

### ISSUE THREAD

**Issue by ArseniiPetrovich** [binance-chain/node-binary#164]
### Short description
The node does not start with the following error: `failed to get rootMultiStore: no data` after the upgrade to 0.6.3-hotfix

### Version
0.6.3-hotfix

### Steps to reproduce

1. Update node binary
2. Recover node to 51467799 height
3. Update node config files
4. Try to run the node.

### Detailed description
We are running two nodes. Today we tried to update them to `0.6.3-hotfix` version.
The first node didn't upgrade with the issue that is described here => https://github.com/binance-chain/node-binary/issues/128
The second node didn't upgrade with an issue that is described here => https://github.com/binance-chain/node-binary/issues/134

This issue is covering the problem with the second node. I've tried to follow the instructions from https://github.com/binance-chain/node-binary/issues/128 and from https://community.binance.org/topic/2176/binance-chain-mainnet-heisenberg-upgrade-announcement also, but no luck - I'm still getting the `no data` error on this node. Could you help, please?

### Additional info
In the forum article there is a following info:
```
Since the height of the upgrade is set to be 51,467,800, you can run the following command to recover the state to just one block before the upgrade, which is 51,467,799 :
./state_recover 4946799 <your_home_path>
```
However, when i tried the `./state_recover 4946799 ./bnbchaind` it didn't work with the following error:
```
[ec2-user@ip-172-31-18-149 linux]$ ./state_recover 4946799 ~/.bnbchaind
recover home_path[/home/ec2-user/.bnbchaind] to height[4946799]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xc48a4e]

goroutine 1 [running]:
main.resetBlockChainState(0x4b7b6f, 0x7fff0ce847c5, 0x19)
	/Users/baifudong/workspace/src/github.com/binance-chain/node/networks/tools/state_recover/state_recover.go:100 +0x39e
main.restartNodeAtHeight(0x4b7b6f, 0x7fff0ce847c5, 0x19)
	/Users/baifudong/workspace/src/github.com/binance-chain/node/networks/tools/state_recover/state_recover.go:250 +0x43
main.main()
	/Users/baifudong/workspace/src/github.com/binance-chain/node/networks/tools/state_recover/state_recover.go:315 +0x1fa

```

It worked only when I used the 51467799 as an argument (`./state_recover 51467799 ~/.bnbchaind
`).

**Comment by ArseniiPetrovich** [comment]
Can it be somehow connected to the change of the `db_backend = "goleveldb"` parameter in the `config.toml` file?

**Comment by ArseniiPetrovich** [comment]
Okay, after recovery the first node went into the same error as described here. So I'll close the #128 again for now

**Comment by ArseniiPetrovich** [comment]
This issue is still actual.

**Comment by huangsuyu** [comment]
Hello, @ArseniiPetrovich 

Thanks for your issue. I think the upgrade height is not reached yet, if your node is going great, just keep it running with v0.6.3-hf.1

**Comment by ArseniiPetrovich** [comment]
@huangsuyu 
Hm... No, my node does not start with the error like: `failed to get rootMultiStore: no data`

**Comment by huangsuyu** [comment]
> @huangsuyu
> Hm... No, my node does not start with the error like: `failed to get rootMultiStore: no data`

have you updated both `config,toml` and `app.toml`?

**Comment by ArseniiPetrovich** [comment]
Yes, I have updated this in my `.bnbchaind/config` directory

**Comment by ArseniiPetrovich** [comment]
The root of the issue was in fact, that I tried to recover state of the node before it actually reached this state. Thus, the node was not able to find the block to start from. Rolled back to a previous block (found latest synced in snapshot folder) and it worked.
