### ISSUE TITLE
升级0.6.3-hotfix节点问题：节点同步一会挂掉，重启之后无法访问通节点

### ISSUE THREAD

**Issue by Victoryfan** [binance-chain/node-binary#167]
Fan Victory, [Nov 30, 2019 at 9:36:18 PM]:
replayed all tx. Starting match              module=dex height=51384149
I[2019-11-30|13:32:18.294] No new orders for any pair, give up matching module=dexkeeper 
I[2019-11-30|13:32:18.294] No order comes in for the block              module=dexkeeper 
I[2019-11-30|13:32:18.294] Relaying block for order book                module=dex height=51384150
I[2019-11-30|13:32:18.294] Canceled Order                               module=dex order="CancelOrderMsg{Sender:2CEC06B72680C73F5608CD0F0BF722DA12BF2F1E, RefId: 2CEC06B72680C73F5608CD0F0BF722DA12BF2F1E-631676}"
I[2019-11-30|13:32:18.294] Added Order                                  module=dex order="NewOrderMsg{Sender: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39, Id: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39-6366182, Symbol: DEFI-FA5_BNB}"
I[2019-11-30|13:32:18.294] replayed all tx. Starting match              module=dex height=51384150
I[2019-11-30|13:32:18.294] Relaying block for order book                module=dex height=51384151

I[2019-11-30|13:32:22.457] No new orders for any pair, give up matching module=dexkeeper 
I[2019-11-30|13:32:22.457] No order comes in for the block              module=dexkeeper 
I[2019-11-30|13:32:22.457] Relaying block for order book                module=dex height=51403817
I[2019-11-30|13:32:22.457] Added Order                                  module=dex order="NewOrderMsg{Sender: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39, Id: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39-6372316, Symbol: DEFI-FA5_BNB}"
I[2019-11-30|13:32:22.457] replayed all tx. Starting match              module=dex height=51403817
I[2019-11-30|13:32:22.457] Relaying block for order book                module=dex height=51403818
I[2019-11-30|13:32:22.457] Added Order                                  module=dex order="NewOrderMsg{Sender: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39, Id: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39-6372317, Symbol: DEFI-FA5_BNB}"
I[2019-11-30|13:32:22.457] replayed all tx. Starting match              module=dex height=51403818
I[2019-11-30|13:32:22.458] Relaying block for order book                module=dex height=51403819
I[2019-11-30|13:32:22.458] Added Order                                  module=dex order="NewOrderMsg{Sender: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39, Id: 37D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39-6372318, Symbol: DEFI-FA5_BNB}"
I[2019-11-30|13:32:22.458] replayed all tx. Starting match              module=dex height=51403819
I[2019-11-30|13:32:22.458] Relaying block for order book                module=dex height=51403820
I[2019-11-30|13:32:22.458] replayed all tx. Starting match              module=dex height=51403820

回滚区块是 51467799

刚开始 回滚完 可以正常同步，但同步一会就挂了，在重启 就会变成这个日志了

**Comment by huangsuyu** [comment]
日志信息显示你的节点在正常同步，没有异常。

**Comment by Victoryfan** [comment]
> 日志信息显示你的节点在正常同步，没有异常。
> 
> 无法访问节点的问题请自行检查`config.toml`中`laddr`端口的连通性。

我们的日志一直是重复这些个高度

**Comment by huangsuyu** [comment]
> > 日志信息显示你的节点在正常同步，没有异常。
> > 无法访问节点的问题请自行检查`config.toml`中`laddr`端口的连通性。
> 
> 我们把laddr的端口改成了7001，最开始同步是可以访问通，但是过一会会挂掉，revert重启后，就一直是重复这些个高度的日志，无法访问。现在是否需要从头开始同步或是使用离线包

节点日志中没有异常报错信息，请检查网络连通性。

请通过`status`端口确认节点的当前高度是否在增长。如果`latest_block_height `一直在增长，说明正在同步。

**Comment by Victoryfan** [comment]
> > > 日志信息显示你的节点在正常同步，没有异常。
> > > 无法访问节点的问题请自行检查`config.toml`中`laddr`端口的连通性。
> > 
> > 
> > 我们把laddr的端口改成了7001，最开始同步是可以访问通，但是过一会会挂掉，revert重启后，就一直是重复这些个高度的日志，无法访问。现在是否需要从头开始同步或是使用离线包
> 
> 节点日志中没有异常报错信息，请检查网络连通性。
> 
> 请通过`status`端口确认节点的当前高度是否在增长。如果`latest_block_height `一直在增长，说明正在同步。

用哪个命令查看？

**Comment by huangsuyu** [comment]
```
curl localhost:27147/status
```
https://docs.binance.org/fullnode.html#monitor-syncing-process

**Comment by Victoryfan** [comment]
> ```
> curl localhost:27147/status
> ```
> 
> https://docs.binance.org/fullnode.html#monitor-syncing-process

那用的是一个命令，现在是rpc连接不上，我们改的是7001端口，端口没生效吗？

**Comment by huangsuyu** [comment]
> > ```
> > curl localhost:27147/status
> > ```
> > 
> > 
> > https://docs.binance.org/fullnode.html#monitor-syncing-process
> 
> 那用的是一个命令，现在是rpc连接不上，刚又看了下日志，一直在513几几和514几几之间重复，重新recover之后，再启动在514722处就挂了。我们现在重新从0开始同步可以吗？

请提供节点的具体报错日志信息。

**Comment by Victoryfan** [comment]
> > > ```
> > > curl localhost:27147/status
> > > ```
> > > 
> > > 
> > > https://docs.binance.org/fullnode.html#monitor-syncing-process
> > 
> > 
> > 那用的是一个命令，现在是rpc连接不上，刚又看了下日志，一直在513几几和514几几之间重复，重新recover之后，再启动在514722处就挂了。我们现在重新从0开始同步可以吗？
> 
> 请提供节点的具体报错日志信息。

没有报错日志，就是循环重复上面的日志信息，然后自己就中断了

**Comment by HaoyangLiu** [comment]
根据你说的现象，我推测可能是你的节点的进程被终止掉，然后你可能是通过服务话的方式启动的节点，所以节点会不断的被再次启动。节点每次启动以后都会replay最近一个呼吸块以来的所有区块。所以你看到了重复的log。
我们更想知道进程为什么被终止，所以请给出更多的log，让我们看到进程终止的原因。

**Comment by Victoryfan** [comment]
> 根据你说的现象，我推测可能是你的节点的进程被终止掉，然后你可能是通过服务话的方式启动的节点，所以节点会不断的被再次启动。节点每次启动以后都会replay最近一个呼吸块以来的所有区块。所以你看到了重复的log。
> 我们更想知道进程为什么被终止，所以请给出更多的log，让我们看到进程终止的原因。

那目前我们可以通过重新从头开始同步来解决问题吗？

**Comment by Victoryfan** [comment]
![Uploading image.png…]()
我重新同步出现这种错误

**Comment by Victoryfan** [comment]
问题已解决，cli问题
