### ISSUE TITLE
Transfer with multi-inputs and multi-outputs -> how are they mapped ?

### ISSUE THREAD

**Issue by razvan-bugheanu-sftle** [binance-chain/node-binary#168]
Hi,

I know that in a transfer message(MessageType.MsgSend (2A2C87FA)), the model uses a list of inputs and a list of outputs.
If it is possible to have more than one input and more than one output, then how is the mapping between inputs-outputs made? Is it based on the index of the items in the lists (e.g. I1 -> O1, I2 -> O2,... In -> On)?

There is no documentation on this aspect, the only thing I could get was from the java-sdk (the model of objects), so please answer this.

**Comment by huangsuyu** [comment]
Hello, @razvan-bugheanu-sftle 

Since there is no support of multisig on Binance Chain, if there are multiple inputs, they should be the same address. For example: https://dex-asiapacific.binance.org/api/v1/tx/21CCBAE89356D79EB4B9BCF406000B49F27C34E8B75B7B1D00C335ECA64AE790?format=json

**Comment by razvan-bugheanu-sftle** [comment]
I think I was not clear enough. Is it possible to have multiple distinct input addresses in a transfer message?

**Comment by huangsuyu** [comment]
> I think I was not clear enough. Is it possible to have multiple distinct input addresses in a transfer message?

yes, you can.

You need to have everyone's signature for this transactions

**Comment by razvan-bugheanu-sftle** [comment]
I am not interested in creating such transactions, it is the monitoring of blockchain transactions I am concerned with. In this regard, it seems impossible to determine a correlation in this form: (from, to, value) when multiple distinct input addresses are present.

**Comment by HaoyangLiu** [comment]
> I am not interested in creating such transactions, it is the monitoring of blockchain transactions I am concerned with. In this regard, it seems impossible to determine a correlation in this form: (from, to, value) when multiple distinct input addresses and multiple distinct output addresses are present.

Yes, you are right. For multiple inputs and multiple outputs, it is not possible to determine a correlation like: (from, to, value)

**Comment by huangsuyu** [comment]
@razvan-bugheanu-sftle close this for now, feel free to reopen in the future, Thanks!
