### ISSUE TITLE
GET /api/v1/timelocks/{address} from HTTP API returns 404

### ISSUE THREAD

**Issue by unjapones** [binance-chain/node-binary#169]
In a project we've been working on, we get a 404 response when doing

```
GET http://{INTERNAL_NODE}/api/v1/timelocks/bnb100dxzy02a6k7vysc5g4kk4fqamr7jhjg4m83l0
```
(this INTERNAL_NODE runs version `0.6.3`)

But when we perform the following on the node that's reference on the documentation, we do get a successfull response:
```
GET https://dex.binance.org/api/v1/timelocks/bnb100dxzy02a6k7vysc5g4kk4fqamr7jhjg4m83l0
```

Are we missing something (config?) that could cause this erroneous behaviour?

**Comment by unjapones** [comment]
cc @ArseniiPetrovich @pablofullana @dminones

**Comment by Wingman4l7** [comment]
Your URL is malformed -- it should be: `api/v1/timelock/timelocks/`

**Comment by unjapones** [comment]
Alright, thanks for the clarification. Closing this now.
