### ISSUE TITLE
怎么启动linux fullnode 节点?

### ISSUE THREAD

**Issue by senhanxiao** [binance-chain/node-binary#171]
怎么启动fullnode 节点?

**Comment by huangsuyu** [comment]
https://docs.binance.org/fullnode.html#start-your-node

**Comment by senhanxiao** [comment]
sh <(wget -qO- https://raw.githubusercontent.com/binance-chain/node-binary/compress/install.sh)

正在把输出重定向至 “wget-log”。
/dev/fd/63: 8: /dev/fd/63: [[: not found
/dev/fd/63: 10: /dev/fd/63: [[: not found
/dev/fd/63: 12: /dev/fd/63: [[: not found
/dev/fd/63: 14: /dev/fd/63: [[: not found
/dev/fd/63: 16: /dev/fd/63: [[: not found
/dev/fd/63: 18: /dev/fd/63: [[: not found
/dev/fd/63: 21: /dev/fd/63: FULLNODE_echo: not found
