### ISSUE TITLE
请教什么情况

### ISSUE THREAD

**Issue by senhanxiao** [binance-chain/node-binary#172]
/60a683de-9524-47a8-a6d0-1a1ec00995682/node-binary/fullnode/testnet/0.6.3/linux$ sudo ./bnbchaind start --home /media/stevenxiao/60a683de-9524-47a8-a6d0-1a1ec00995682/node-binary-data/.bnbchaind/ 
panic: Value missing for hash 7d1d02862789f7fb7e094597dc0369966eba8c06c1dc42ae4592aff7cd056477 corresponding to nodeKey n}�'���~	E��i�n����B�E����dw

goroutine 1 [running]:
github.com/tendermint/iavl.(*nodeDB).GetNode(0xc000ad4b10, 0xc00f662b80, 0x20, 0x20, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/nodedb.go:68 +0x482
github.com/tendermint/iavl.(*Node).getRightNode(0xc00f677bc0, 0xc000142d40, 0x0, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:413 +0x195
github.com/tendermint/iavl.(*Node).get(0xc00f677bc0, 0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0x21, 0x1, 0xc000ad50b0, 0x172d5c8)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:190 +0x218
github.com/tendermint/iavl.(*Node).get(0xc00f677b00, 0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0x1e, 0xffffffffffffffff, 0xc000ad50b0, 0x172d5c8)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc00f677a40, 0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0x20, 0x1, 0xc000ad50b0, 0x172d5c8)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:188 +0x1bd
github.com/tendermint/iavl.(*Node).get(0xc00f677980, 0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0x1e, 0x1, 0x41a309, 0xc00f6817a0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc00f6778c0, 0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0x1f, 0x1, 0x1344080, 0x41a309)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:191 +0x256
github.com/tendermint/iavl.(*Node).get(0xc000236540, 0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0xc00f662880, 0x2605740, 0xc000c0e580, 0xc0001c4a80)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:191 +0x256
github.com/tendermint/iavl.(*ImmutableTree).Get(0xc000142d40, 0xc00f662880, 0x1e, 0x20, 0xc000000008, 0xc000142a00, 0xc0001a6340, 0xc000d25f10)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/immutable_tree.go:154 +0x6a
github.com/cosmos/cosmos-sdk/store.(*IavlStore).Get(0xc0001fcae0, 0xc00f662880, 0x1e, 0x20, 0x2727560, 0xc00f662800, 0x1e)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/store/iavlstore.go:153 +0x4f
github.com/cosmos/cosmos-sdk/store.(*cacheKVStore).Get(0xc000477140, 0xc00f662880, 0x1e, 0x20, 0x0, 0x0, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/store/cachekvstore.go:50 +0x125
github.com/binance-chain/node/plugins/dex/order.(*Keeper).LoadOrderBookSnapshot(0xc000a83c70, 0x19113e0, 0xc000d56990, 0xc00003cd00, 0xb, 0x0, 0x142b7d8, 0xed58a31ae, 0x0, 0x0, ...)
	/home/suyu/go/src/github.com/binance-chain/node/plugins/dex/order/keeper_recovery.go:123 +0x927
github.com/binance-chain/node/plugins/dex/order.(*Keeper).initOrderBook(0xc000a83c70, 0x19113e0, 0xc000d56990, 0xc00003cd00, 0xb, 0x0, 0x7, 0xc000d26590, 0x192b1c0, 0xc00013c450, ...)
	/home/suyu/go/src/github.com/binance-chain/node/plugins/dex/order/keeper_recovery.go:270 +0xce
github.com/binance-chain/node/plugins/dex/order.(*Keeper).Init(0xc000a83c70, 0x19113e0, 0xc000d56990, 0xc00003cd00, 0xb, 0x0, 0x7, 0xc000d26590, 0x192b1c0, 0xc00013c450, ...)
	/home/suyu/go/src/github.com/binance-chain/node/plugins/dex/order/keeper.go:94 +0xbb
github.com/binance-chain/node/app.(*BinanceChain).initDex(0xc000108600, 0x1920000, 0xc000a80e60)
	/home/suyu/go/src/github.com/binance-chain/node/app/app.go:320 +0x335
github.com/binance-chain/node/app.NewBinanceChain(0x19127a0, 0xc000d80d20, 0x192b1c0, 0xc000012698, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100)
	/home/suyu/go/src/github.com/binance-chain/node/app/app.go:241 +0x1c22
main.newApp(0x19127a0, 0xc000d80d20, 0x192b1c0, 0xc000012698, 0x0, 0x0, 0xc000d84000, 0xc000c51920)
	/home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:23 +0x78
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0001fc520, 0x172cc40, 0x1d, 0x0, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/server/start.go:117 +0x187
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc00012b400, 0xc0001fc860, 0x0, 0x2, 0x0, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/server/start.go:44 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc00012b400, 0xc0001fc820, 0x2, 0x2, 0xc00012b400, 0xc0001fc820)
	/home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000454c80, 0x2, 0xc0001fc780, 0x15bcb05)
	/home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000454c80, 0x172d058, 0x2, 0xc00026a400)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/libs/cli/setup.go:89 +0x3c
main.main()
	/home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef

**Comment by senhanxiao** [comment]
日志:
I[2019-12-17|10:16:40.959] Starting ABCI with Tendermint                module=main
I[2019-12-17|10:16:43.002] Located day to load breathe block height     module=dexkeeper epochDay="FG\u0000\u0000\u0000\u0000\u0000\u0000"
I[2019-12-17|10:16:43.002] Loaded breathe block height                  module=dexkeeper height=55326822
I[2019-12-17|10:16:43.002] Loading order book snapshot from last breathe block module=main blockHeight=55326822
I[2019-12-17|10:17:17.645] Starting ABCI with Tendermint                module=main
I[2019-12-17|10:17:18.023] Located day to load breathe block height     module=dexkeeper epochDay="FG\u0000\u0000\u0000\u0000\u0000\u0000"
I[2019-12-17|10:17:18.024] Loaded breathe block height                  module=dexkeeper 

height=55326822
I[2019-12-17|10:17:18.024] Loading order book snapshot from last breathe block module=main blockHeight=55326822
I[2019-12-17|10:32:40.105] Starting ABCI with Tendermint                module=main
I[2019-12-17|10:32:40.507] Located day to load breathe block height     module=dexkeeper epochDay="FG\u0000\u0000\u0000\u0000\u0000\u0000"
I[2019-12-17|10:32:40.507] Loaded breathe block height                  module=dexkeeper height=55326822
I[2019-12-17|10:32:40.507] Loading order book snapshot from last breathe block module=main blockHeight=55326822
~

**Comment by huangsuyu** [comment]
@senhanxiao 从后一个日志输出看来，节点在正常运行。

**Comment by senhanxiao** [comment]
@huangsuyu  stevenxiao@bufeng:/media/stevenxiao/60a683de-9524-47a8-a6d0-1a1ec00995682/node-binary/fullnode/testnet/0.6.3-hotfix$ curl 'localhost:26657/status'
{ }
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "0"
      },
      "id": "d3fb19340699d2427b5c5e89b840cfa9c6696eb4",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "Binance-Chain-Nile",
      "version": "0.32.3",
      "channels": "36402021222330380041",
      "moniker": "xxx",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:26657"
      }
    },
    "sync_info": {
      "latest_block_hash": "898E587A407C7835AA206DFC38DCE607A3D55EA78D8A1B6D81C6E9A8C68D0220",
      "latest_app_hash": "47DB6B06DCA525522D94FA5DC1E696A45254ED57D2F2692EADE5F0832494AF63",
      "latest_block_height": "55688017",
      "latest_block_time": "2019-12-18T00:00:00.298614404Z",
      "catching_up": true,
      "index_height": "0"
    },
    "validator_info": {
      "address": "4A393AC507A0344BF895D3C4C55654F6E06DCFC9",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "vppXX0NTqmiYrmCYUMY/xGkn2sLinfx5wVjrml6ahQA="
      },
      "voting_power": "0"
    }
  }
}

**Comment by senhanxiao** [comment]
curl 'localhost:26657/block?height=53576950'
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "block_meta": null,
    "block": null
  }
}

**Comment by huangsuyu** [comment]
你的节点还在同步中

**Comment by milu2003** [comment]
@senhanxiao 你的测试网有没有安装成功啊？
