### ISSUE TITLE
Problem starting node ( testnet version 0.6.3-hotfix)

### ISSUE THREAD

**Issue by hickwa** [binance-chain/node-binary#174]
panic: ERROR:
Codespace: 5
Code: 9
Message: "Initial ProposalID already set"

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/gov.InitGenesis(0x19112a0, 0xc0137531a0, 0xc01081ed00, 0xb, 0xc0000f29a0, 0x18fd7e0, 0xc00001a230, 0x18fd820, 0xc00001a2a0, 0xc000bff1a0, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/x/gov/genesis.go:49 +0x35c
github.com/binance-chain/node/app.(*BinanceChain).initChainerFn.func1(0x19112a0, 0xc0137531a0, 0xc01081ed00, 0xb, 0x1ddb536b, 0xed4127047, 0x0, 0xc00e539680, 0x12, 0xc01081e7c0, ...)
	/home/suyu/go/src/github.com/binance-chain/node/app/app.go:380 +0x7b2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000b931d0, 0x1ddb536b, 0xed4127047, 0x0, 0xc00e539680, 0x12, 0xc01081e7c0, 0x2725bf0, 0x0, 0x0, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/baseapp/baseapp.go:354 +0x19f
github.com/cosmos/cosmos-sdk/server/concurrent.(*asyncLocalClient).InitChainSync(0xc0000d5d90, 0x1ddb536b, 0xed4127047, 0x0, 0xc00e539680, 0x12, 0xc01081e7c0, 0x2725bf0, 0x0, 0x0, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/server/concurrent/async_local_client.go:385 +0xec
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc00544d8f0, 0x1ddb536b, 0xed4127047, 0x0, 0xc00e539680, 0x12, 0xc01081e7c0, 0x2725bf0, 0x0, 0x0, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/proxy/app_conn.go:103 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000ca6780, 0xa, 0x0, 0xc013522026, 0x6, 0xc00e539780, 0x12, 0x3547fa8, 0x2c63041, 0xc00e5397a0, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/consensus/replay.go:313 +0x68f
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000ca6780, 0x192d600, 0xc0054fcfc0, 0x149a180, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/consensus/replay.go:271 +0x61e
github.com/tendermint/tendermint/node.doHandshake(0x192b080, 0xc006d8ca98, 0xa, 0x0, 0xc013522026, 0x6, 0xc00e539780, 0x12, 0x3547fa8, 0x2c63041, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/node/node.go:313 +0x211
github.com/tendermint/tendermint/node.NewNode(0xc000958c60, 0x190a520, 0xc00560a780, 0xc00544c610, 0x18ea320, 0xc004f81a40, 0xc00544c890, 0x172c1d0, 0xc00544c8a0, 0x1912660, ...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/node/node.go:649 +0x497
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000152a80, 0x172cb80, 0x1d, 0x0, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/server/start.go:133 +0x57e
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000b8f400, 0xc000152dc0, 0x0, 0x2, 0x0, 0x0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/server/start.go:44 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000b8f400, 0xc000152d80, 0x2, 0x2, 0xc000b8f400, 0xc000152d80)
	/home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012f400, 0x2, 0xc000152ce0, 0x15bca4a)
	/home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00012f400, 0x172cf98, 0x2, 0xc0009b2d90)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/libs/cli/setup.go:89 +0x3c
main.main()
	/home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3ef

**Comment by huangsuyu** [comment]
Hello, @hickwa 

It seems that you restarted your node when the thread is not properly killed. Please clear your home directory by
```
bnbchaind unsafe-reset-all --home<your-home-dir>
```

And start again. 

Thanks!
