### ISSUE TITLE
curl 'localhost:27147/block?height=10'

### ISSUE THREAD

**Issue by senhanxiao** [binance-chain/node-binary#176]
该接口返回的交易信息没有交易hash吗？怎么获取block中的所有交易信息，包含交易hash

**Comment by senhanxiao** [comment]
@huangsuyu 请教 轮训区块，不能取得交易的HASH吗？或者怎么可以取到？

**Comment by huangsuyu** [comment]
> @huangsuyu 请教 轮训区块，不能取得交易的HASH吗？或者怎么可以取到？

请参考这个例子： https://github.com/binance-chain/node-binary/issues/53#issuecomment-500687304
