### ISSUE TITLE
failed to load rootMultiStore

### ISSUE THREAD

**Issue by dingyo777** [binance-chain/node-binary#178]
My full node seems like crash because of reacting lately for hard fork.

So I followed this manual: https://docs.binance.org/fullnodeissue.html#forget-to-upgrade

After successfully running command like below
```
ubuntu@production:~$ ./state_recover 41276999 .bnbchaind/
recover home_path[.bnbchaind/] to height[41276999]
recover success
```

when I runs `bnbchaind start &`,
 
I got below error message.
```
ubuntu@production:~/node-binary-0.6.2/fullnode/prod/0.6.2/linux$ failed to load rootMultiStore: wanted to load target 41276999 but only found up to 41270000
```

May I get your favor how to handle this issue?

**Comment by huangsuyu** [comment]
Hello, @dingyo777 

Which version of `bnbchaind` did you use to restart?

**Comment by dingyo777** [comment]
@huangsuyu 
Thank you for your response :)
I used 0.6.2

**Comment by huangsuyu** [comment]
> @huangsuyu
> Thank you for your response :)
> I used 0.6.2

hello, @dingyo777 

Did you replace your config files to v0.6.2?(both `config.toml` and `app.toml`)

**Comment by dingyo777** [comment]
@huangsuyu 
Yes, I changed `config.toml` and `app.toml` of v0.6.2 to `.bnbchaind`

**Comment by huangsuyu** [comment]
> @huangsuyu
> Yes, I changed `config.toml` and `app.toml` of v0.6.2 to `.bnbchaind`

are you using `~/.bnbchaind` as your home folder for `bnbchaind`?

**Comment by huangsuyu** [comment]
Thanks @dingyo777 

I just noticed that the upgrade height is `41277000 ` which is different from your log `41270000 `. please double check your `app.toml` file
https://github.com/binance-chain/node-binary/blob/master/fullnode/prod/0.6.2/config/app.toml

**Comment by dingyo777** [comment]
@huangsuyu 
Thank you for your confirmation 
I will check :)
