### ISSUE TITLE
filter transaction for the specified account

### ISSUE THREAD

**Issue by hickwa** [binance-chain/node-binary#179]
Is there a configuration that can filter transactions for the specified account?

**Comment by huangsuyu** [comment]
> Is there a configuration that can filter transactions for the specified account?

Hello,  you can use this API: https://docs.binance.org/api-reference/dex-api/paths.html#apiv1transactions?

for example: `https://dex.binance.org/api/v1/transactions?address=bnb1ywyqna0ne50c7rqc6mawtml923pk9x793sa8yk&startTime=1564934400000`

**Comment by hickwa** [comment]
Any api for node rpc to implement the function?
Does the api you mentioned above support ascending order of blockHeight or timeStamp?

**Comment by huangsuyu** [comment]
> Any api for node rpc to implement the function?
> Does the api you mentioned above support ascending order of blockHeight or timeStamp?

The returned transactions are in decending order
