### ISSUE TITLE
error: ./bnbcli can't execute

### ISSUE THREAD

**Issue by gtygo** [binance-chain/node-binary#181]
who to fix this problem?
os: ubuntu

./bnbcli: line 1: version: command not found
./bnbcli: line 2: oid: command not found
./bnbcli: line 3: size: command not found

**Comment by huangsuyu** [comment]
Hello, @gtygo 

all the binaries are uploaded to `git lfs`. Please use `wget` to download the whole fine or use this script: https://github.com/binance-chain/node-binary#installation-script

**Comment by huangsuyu** [comment]
Close this now, please reopen when necessary.
