### ISSUE TITLE
error:dialing failed (attempts: 3) testnet

### ISSUE THREAD

**Issue by shenyaqi9527** [binance-chain/node-binary#182]
`E[2020-01-13|16:36:38.465] dialing failed (attempts: 3): incompatible: Peer is on a different network. Got Binance-Chain-Tigris, expected Binance-Chain-Nile module=pex addr=cfb5c1f7c10dfd99219158f5491ce65227bfd072@99.80.184.64:27146`
What about this?

**Comment by huangsuyu** [comment]
Hello, @shenyaqi9527 

It can be a warning message and you can ignore it.

**Comment by shenyaqi9527** [comment]
`
 chunkCompletion=0
I[2020-01-13|16:37:50.522] finished write recovery chunk                module=statesync isComplete=true hash=a60a396070408fe60c0766fc9d35dc889e140678e81415b2c5559d7f37d0876a startIdx=1419704 numOfNodes=0 chunkCompletion=0
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x15a4255, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc214000000, 0x90000000, 0x2728198)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x270eda0, 0x8d5f0000, 0x270edb0, 0x46af8)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x270eda0, 0x46af8, 0x0)
	/usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x270eda0, 0x46af8, 0x27281a8, 0x0)
	/usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x270eda0, 0x46af8, 0x101, 0x0)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x270eda0, 0x46af8, 0x7ff1f3010101, 0x4350f0)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x8d5eef1d, 0x460101, 0xc208000000)
	/usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

`
执行一段时间后就出现了这个
是我内存不够吗

**Comment by shenyaqi9527** [comment]
我现在内存是8g，但是主网我用的也是8g他现在在同步，测试网要的内存还要比主网高吗

**Comment by huangsuyu** [comment]
> @huangsuyu 我现在内存是8g，但是主网我用的也是8g他现在在同步，测试网要的内存还要比主网高吗

8G内存肯定够用了。

**Comment by shenyaqi9527** [comment]
@huangsuyu 我测试节点重启了几次都是这样的情况

**Comment by huangsuyu** [comment]
> @huangsuyu 我测试节点重启了几次都是这样的情况

8G内存肯定够用了。
![image](https://user-images.githubusercontent.com/48426112/72400299-c98e2180-3783-11ea-8edd-4c0c021e326c.png)

你能不能把日志级别调为debug，查看是否是其他问题。
在`config.toml`中将log_level改为`log_level = "*:debug"`

**Comment by huangsuyu** [comment]
Hello, I will close this now. Please reopen when necessary.

**Comment by milu2003** [comment]
@shenyaqi9527  @huangsuyu  搞定了没？测试网折腾2天了，老是安装不成功。你们可以安装成功吗
