### ISSUE TITLE
panic: Value missing for hash 9f

### ISSUE THREAD

**Issue by senhanxiao** [binance-chain/node-binary#185]
全节点同步 
同步两次都是报
panic: Value missing for hash 9f06af4ae7aec27ef81c7b0cc41088125775cfad3efb3323753fcf3be9f4db63 corresponding to nodeKey n��J��~�{��Wuϭ>�3#u?�;���c

**Comment by senhanxiao** [comment]
@huangsuyu 请教

**Comment by senhanxiao** [comment]
ubuntu@bdes-bn:~/0.6.3-hotfix/linux$ ./bnbchaind start
panic: Value missing for hash 9f06af4ae7aec27ef81c7b0cc41088125775cfad3efb3323753fcf3be9f4db63 corresponding to nodeKey n��J��~�{��Wuϭ>�3#u?�;���c

goroutine 38 [running]:
github.com/tendermint/iavl.(*nodeDB).GetNode(0xc000d784e0, 0xc00fe436a0, 0x20, 0x20, 0x0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/nodedb.go:68 +0x482
github.com/tendermint/iavl.(*Node).getRightNode(0xc00fe91a40, 0xc00096d5c0, 0x0, 0x0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:413 +0x195
github.com/tendermint/iavl.(*Node).traverseInRange(0xc00fe91a40, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10a0001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:507 +0x128
github.com/tendermint/iavl.(*Node).traverseInRange(0xc00fe91980, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1090001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:501 +0x295
github.com/tendermint/iavl.(*Node).traverseInRange(0xc00fe918c0, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1080001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:501 +0x295
github.com/tendermint/iavl.(*Node).traverseInRange(0xc00fe906c0, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1070001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:507 +0x1c1
github.com/tendermint/iavl.(*Node).traverseInRange(0xc00fe90600, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1060001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:501 +0x295
github.com/tendermint/iavl.(*Node).traverseInRange(0xc00fe2c180, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1050001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:507 +0x1c1
github.com/tendermint/iavl.(*Node).traverseInRange(0xc003f77b00, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1040001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:507 +0x1c1
github.com/tendermint/iavl.(*Node).traverseInRange(0xc000da5080, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1030001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:507 +0x1c1
github.com/tendermint/iavl.(*Node).traverseInRange(0xc0000c0c00, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x20001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:507 +0x1c1
github.com/tendermint/iavl.(*Node).traverseInRange(0xc0000c0b40, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10001, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:501 +0x295
github.com/tendermint/iavl.(*Node).traverseInRange(0xc0000c0480, 0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00088bf48, ...)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/node.go:501 +0x295
github.com/tendermint/iavl.(*ImmutableTree).IterateRange(0xc00096d5c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000e8d7b8, 0x0)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint-iavl@v0.12.0-binance.3/immutable_tree.go:203 +0xdc
github.com/cosmos/cosmos-sdk/store.(*iavlIterator).iterateRoutine(0xc0000ca280)
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/store/iavlstore.go:317 +0x95
created by github.com/cosmos/cosmos-sdk/store.newIAVLIterator
        /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.21/store/iavlstore.go:310 +0x18b

**Comment by huangsuyu** [comment]
你好 @senhanxiao 

请问你的节点是运行在测试网还是主网？

请确认是否更新了配置文件 `app.toml` 和 `config.toml`：https://github.com/binance-chain/node-binary/tree/master/fullnode/testnet/0.6.3-hotfix/config

谢谢！

**Comment by huangsuyu** [comment]
Close thie now, please reopen when necessary.
