### ISSUE TITLE
 start &panic: {"codespace":4,"code":101,"abci_code":262245,"message":"validator already exist for this operator address, must use new validator operator address"}

### ISSUE THREAD

**Issue by senhanxiao** [binance-chain/node-binary#189]
start &panic: {"codespace":4,"code":101,"abci_code":262245,"message":"validator already exist for this operator address, must use new validator operator address"}

**Comment by senhanxiao** [comment]
@huangsuyu  请教同步，testnet 0.6.3 hotfix  ,配置文件新的，没有变动。这是什么情况？

**Comment by huangsuyu** [comment]
你好，请问能不能提供你的启动命令？
请确认已经将测试网配置文件拷贝到了`home/config`？
https://docs.binance.org/fullnode.html#setup-configuration

**Comment by huangsuyu** [comment]
I will close this now, please reopen when necessory~
