### ISSUE TITLE
Node Setup

### ISSUE THREAD

**Issue by Introdus** [binance-chain/node-binary#198]
Greetings,

After following the setup instructions to run a node i get the following error when trying to run a node with

 >  bnbchaind start --home $BNCHOME&

> panic: runtime error: slice bounds out of range
> 
> goroutine 1 [running]:
> github.com/spf13/viper.absPathify(0xc00008e0a0, 0x8, 0x1527571, 0x4)
>         /home/suyu/go/pkg/mod/github.com/spf13/viper@v1.4.0/util.go:100 +0x450
> github.com/spf13/viper.(*Viper).AddConfigPath(0xc0000c8200, 0xc00008e0a0, 0x8)
>         /home/suyu/go/pkg/mod/github.com/spf13/viper@v1.4.0/viper.go:413 +0x69
> github.com/spf13/viper.AddConfigPath(...)
>         /home/suyu/go/pkg/mod/github.com/spf13/viper@v1.4.0/viper.go:410
> github.com/tendermint/tendermint/libs/cli.bindFlagsLoadViper(0xc000167b80, 0xc0000808a0, 0x0, 0x2, 0xc000c65cc0, 0x5c5010)
>         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/libs/cli/setup.go:134 +0x160
> github.com/tendermint/tendermint/libs/cli.concatCobraCmdFuncs.func1(0xc000167b80, 0xc0000808a0, 0x0, 0x2, 0x0, 0x0)
>         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/libs/cli/setup.go:115 +0x84
> github.com/spf13/cobra.(*Command).execute(0xc000167b80, 0xc0000804a0, 0x2, 0x2, 0xc000167b80, 0xc0000804a0)
>         /home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:805 +0x577
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bca00, 0x2, 0xc00008df00, 0x15589d4)
>         /home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x303
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/suyu/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
> github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000bca00, 0x16c91f8, 0x2, 0x1535047)
>         /home/suyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/libs/cli/setup.go:89 +0x43
> main.main()
>         /home/suyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:54 +0x3f6

Any help greatly appreciated

**Comment by huangsuyu** [comment]
Hello, @Introdus 

Please make sure that you have downloaded all config files in to you `$BNCHOME/config`

Then, run `bnbchaind unsafe-reset-all --home $NBCHOME` and start again

**Comment by huangsuyu** [comment]
Close this now, please reopen when necessary.
