### ISSUE TITLE
Question about the result of a success/fail in transaction

### ISSUE THREAD

**Issue by leeheejoo** [binance-chain/node-binary#199]
In the transaction section below, can I find out what is the result of the transaction success or fail?

{
   "jsonrpc": "2.0",
   "id": "",
   "result": {
      "hash": "AB1B84C7C0B0B195941DCE9CFE1A54214B72D5DB54AD388D8B146A6B62911E8E",
      "height": "7560096",
      "index": 0,
      "tx_result": {
         "data": "eyJvcmRlcl9pZCI6IjgxM0U0OTM5RjE1NjdCMjE5NzA0RkZDMkFENERGNThCREUwMTA4NzktNDMifQ==",
         "log": "Msg 0: ",
         "tags": [
            {
               "key": "YWN0aW9u",
               "value": "b3JkZXJOZXc="
            }
         ]
      },
      "tx": "2wHwYl3uCmPObcBDChSBPkk58VZ7IZcE/8KtTfWL3gEIeRIrODEzRTQ5MzlGMTU2N0IyMTk3MDRGRkMyQUQ0REY1OEJERTAxMDg3OS00MxoNWkVCUkEtMTZEX0JOQiACKAEwwIQ9OJBOQAEScAom61rphyECE5vdld5ywirCorD4eFOxzKLorfnFikponHXTJjATRBoSQFmMOnTcCNgtl2aO01I6EFoq+3UsW+NNCftfMVjVXbL1RaJGYmPPgPAtEYTdUO/E2KY2omKQmmMuvt3qpCbAkrIY0uUYICo="
   }
}

**Comment by huangsuyu** [comment]
Hello, @leeheejoo 

Here is an example: https://github.com/binance-chain/node-binary/issues/53#issuecomment-500687304

**Comment by leeheejoo** [comment]
Thank you for answer.
I also tried decoding the transaction to go-sdk. However, the decoded json tx has no property as to whether this transaction was successful or unsuccessful.

The json below is the directly decoded json.

{"msg":[{"inputs":[{"address":"bnb1l6dxh9kz055vs0qkdn3n43y6tez38csj4q7x5d","coins":[{"denom":"BNB","amount":35012840862}]}],"outputs":[{"address":"bnb1lc5c3paqzh55d7n7zd6dgvhaqq5905wzr849tj","coins":[{"denom":"BNB","amount":35012840862}]}]}],"signatures":[{"pub_key":[3,165,86,194,182,176,112,115,122,16,46,98,131,28,150,125,18,116,161,70,233,71,121,53,154,100,138,255,227,113,66,81,75],"signature":"P66nAeKx/671oBzc37WRnxxXCOxmIJOdCCZEEeSxiv1ualjMoI7sKDiZoTHzS6e1mpjqIa2MHYEM/Tq99+BfCQ==","account_number":27586,"sequence":77}],"memo":"","source":0,"data":null}


The following is the tx content of Cosmos (atom). In the json content below, there is a success or failure of the transaction in the raw_log(... "success\":true ...) property.

**I want to know the success / failure of tx like this.**

{
  "height": "1198388",
  "txhash": "90A74B103841FE9D503DAAABC9F3D8FE7FAB853238CA7776498F9C269498467E",
  "raw_log": "[{\"msg_index\":0,\**"success\":true**,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"sender\",\"value\":\"cosmos1a2ehrtg2e557t5r093dgqrcu4jk4t80r6nlvye\"},{\"key\":\"module\",\"value\":\"bank\"},{\"key\":\"action\",\"value\":\"multisend\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"cosmos144fzpepuvdftv4u4r9kq8t35ap2crruv4u3udz\"}]}]}]",
  "logs": [
    {
      "msg_index": 0,
      "success": true,
      "log": "",
      "events": [
        {
          "type": "message",
          "attributes": [
            {
              "key": "sender",
              "value": "cosmos1a2ehrtg2e557t5r093dgqrcu4jk4t80r6nlvye"
            },
            {
              "key": "module",
              "value": "bank"
            },
            {
              "key": "action",
              "value": "multisend"
            }
          ]
        },
        {
          "type": "transfer",
          "attributes": [
            {
              "key": "recipient",
              "value": "cosmos144fzpepuvdftv4u4r9kq8t35ap2crruv4u3udz"
            }
          ]
        }
      ]
    }
  ],
  "gas_wanted": "200000",
  "gas_used": "38825",
  "tx": {
    "type": "cosmos-sdk/StdTx",
    "value": {
      "msg": [
        {
          "type": "cosmos-sdk/MsgMultiSend",
          "value": {
            "inputs": [
              {
                "address": "cosmos1a2ehrtg2e557t5r093dgqrcu4jk4t80r6nlvye",
                "coins": [
                  {
                    "denom": "uatom",
                    "amount": "2899000"
                  }
                ]
              }
            ],
            "outputs": [
              {
                "address": "cosmos144fzpepuvdftv4u4r9kq8t35ap2crruv4u3udz",
                "coins": [
                  {
                    "denom": "uatom",
                    "amount": "2899000"
                  }
                ]
              }
            ]
          }
        }
      ],
      "fee": {
        "amount": [
          {
            "denom": "uatom",
            "amount": "1000"
          }
        ],
        "gas": "200000"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "AwbbZTyim6tYHvwnkeF9i7N/Z84CrvXNH5pEVhpwf/jB"
          },
          "signature": "R29PEYhEVxOBAV39KRreNWnFFomoLXtXAPjrz00b0uIVhnZI9KPiF7xq/IiLrPUxjKG6cX+2dgcNa7yyP8fdcQ=="
        }
      ],
      "memo": ""
    }
  },
  "timestamp": "2020-03-19T05:28:15Z",
  "events": [
    {
      "type": "message",
      "attributes": [
        {
          "key": "sender",
          "value": "cosmos1a2ehrtg2e557t5r093dgqrcu4jk4t80r6nlvye"
        },
        {
          "key": "module",
          "value": "bank"
        },
        {
          "key": "action",
          "value": "multisend"
        }
      ]
    },
    {
      "type": "transfer",
      "attributes": [
        {
          "key": "recipient",
          "value": "cosmos144fzpepuvdftv4u4r9kq8t35ap2crruv4u3udz"
        }
      ]
    }
  ]
}

**Comment by huangsuyu** [comment]
Hello, @leeheejoo 
You can use this function to get transaction result: https://github.com/binance-chain/go-sdk/blob/master/client/basic/basic.go#L68

**Comment by leeheejoo** [comment]
Thank you for your answer.
I found that there is a Code property in TxResult / TxCommitResult in the link below.
[https://github.com/binance-chain/go-sdk/blob/master/types/tx/result.go](url)
If the Code value is 0, does it mean success? And other values mean failure?

  I want to know if the tx is a success when it is included in a block after tx propagation. and if the success / failure can be found by Code value or else.

![캡처](https://user-images.githubusercontent.com/15276546/77427939-a3879c00-6e1a-11ea-9e53-f63077e8c36c.PNG)

**Comment by huangsuyu** [comment]
yes, Code 0 means that the transaction is successful.

**Comment by leeheejoo** [comment]
thank you ~ ^^

**Comment by DogoninAleksandr** [comment]
> yes, Code 0 means that the transaction is successful.

exactly it's true?
I see a transaction with code: 65539, it a correct transaction?

"result": {
    "hash": "6BB6459074E0E2F5895B518B2B79B73836FB6226EC89BDA07A2169722B7EE56C",
    "height": "178830727",
    "index": 2,
    "tx_result": {
      "code": 65539,
      "log": "{\"codespace\":1,\"code\":3,\"abci_code\":65539,\"message\":\"Invalid sequence. Got 9093055, expected 7407405\"}",
      "events": [
        {}
      ]
    }
