### ISSUE TITLE
Transactions Stuck in testnet

### ISSUE THREAD

**Issue by APshenkin** [binance-chain/node-binary#200]
https://seed-pre-s3.binance.org/unconfirmed_txs

There is two unconfirmed transactions, that stucks in testnet.
```
"wgHwYl3uCkoqLIf6CiEKFAtfykLx3NFcXb6Jy7Dqo9JLoC7QEgkKA0JOQhDE3zoSIQoUJLdBi7orIbcXJ2i9Pp99iuMtIMYSCQoDQk5CEMTfOhJwCibrWumHIQM1TfEO7h5b/LoKHRgw2ejyYU1mRQeIuuAT68EFyplOSBJAjxARbYaNy4EFqtgxvxsMEE0aNA89iUlNSoJzgr2ETBcoh4ncHoKCeOji5KiC7X4mHHB1rhANPbHEQ5Xvr8RkORiXwiogeQ==",
"wgHwYl3uCkoqLIf6CiEKFAtfykLx3NFcXb6Jy7Dqo9JLoC7QEgkKA0JOQhDE3zoSIQoUJLdBi7orIbcXJ2i9Pp99iuMtIMYSCQoDQk5CEMTfOhJwCibrWumHIQM1TfEO7h5b/LoKHRgw2ejyYU1mRQeIuuAT68EFyplOSBJAheXPXLulr8I/5UquANiiFYy2ewlIU7NrXhlXvP23HP81mZOdLyMpHYRs42LDINZbe0p9dxc5An5OfA/R0DRTBBiXwiogeg=="
```
What is wrong with them and why they stuck?

**Comment by APshenkin** [comment]
So I broadcast these txs by this node https://data-seed-pre-0-s3.binance.org/

and then they disappears from list of unconfirmed. But anyway it seems that https://seed-pre-s3.binance.org can't publish transaction

**Comment by huangsuyu** [comment]
Hello, @APshenkin 

This issue has been fixed. it turns out this node had connectivity issue~
