### ISSUE TITLE
Read data.trx

### ISSUE THREAD

**Issue by rommzestz** [binance-chain/node-binary#202]
when execute

curl http://localhost:27147/block_result?height=84275013

fullnode return json 
when one of urgent part is data.trx contain somethink

"data": {
        "txs": [
          "6QHwYl3uCm7ObcBDChQUaO5BLDrcnP8+8xrcft0oj14gjhIwMTQ2OEVFNDEyQzNBREM5Q0ZGM0VGMzFBREM3RUREMjg4RjVFMjA4RS00MDQ2NTMyGg9FT1NCVUxMLUYwRF9CTkIgAigCMPCyzhI4gL7Dx3xAARJzCibrWumHIQN71QxNe08M6356bk2a6vV44SNkfxQb6DJo5F3sUPjM1RJAkafsi7S+UEE9bAR8Cv4xnv9NQIbMczKxcaq86Bycpbh326XRVaR4sCw1Z8n+SePk4d8AYTsucxrAFbLBNRubKRiMwBQgw/32AQ=="
        ]

how i can receive JSON from this data?

**Comment by huangsuyu** [comment]
Hello, @rommzestz 
You could use SDK for decoding the data: https://github.com/binance-chain/go-sdk/blob/95a9c206b2e47168550b3d68d8ec56519a4d9061/e2e/e2e_rpc_test.go#L195
