### ISSUE TITLE
Failed to process committed block 

### ISSUE THREAD

**Issue by abyssal0** [binance-chain/node-binary#207]
panic: Failed to process committed block (90913099:6EAF26E7AA83DD2B2513CA432793847B50E8243EDBBF992BB79D8C2568F6FEDA): Wrong Block.Header.AppHash.  Expected A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C, got 1F7F6326657EB801001C4E49848D882551B3F2B4CA1259CF533E3F1BE8AFD339

What should I do?

**Comment by IvanDedov** [comment]
> panic: Failed to process committed block (90913099:6EAF26E7AA83DD2B2513CA432793847B50E8243EDBBF992BB79D8C2568F6FEDA): Wrong Block.Header.AppHash. Expected A74D98958D7A6D4EDFFBBF760EDE9A27DF9141A379DBB1E55F5A6AF71C5D3A2C, got 1F7F6326657EB801001C4E49848D882551B3F2B4CA1259CF533E3F1BE8AFD339
> 
> What should I do?

Hello! Check it looks like your case. https://github.com/binance-chain/node-binary/issues/204
