### ISSUE TITLE
Planned forks

### ISSUE THREAD

**Issue by ArseniiPetrovich** [binance-chain/node-binary#208]
Hi, guys. Is there any major updates are upcoming (like 0.6.3)? I was not able to find info on your website.

**Comment by huangsuyu** [comment]
Hello, @ArseniiPetrovich 

Binance Chain Testnet has already upgraded to v0.7.0: https://community.binance.org/topic/2828/binance-chain-testnet-nightingale-upgrade-complete

Please wait for mainnet upgrade announcement.
