### ISSUE TITLE
version: command not found

### ISSUE THREAD

**Issue by hickwa** [binance-chain/node-binary#211]
git lfs clone https://github.com/binance-chain/node-binary.git
cd node-binary/fullnode/testnet/0.7.0/linux
./bnbchaind --help
./bnbchaind: line 1: version: command not found
./bnbchaind: line 2: oid: command not found
size: '44177463': No such file

**Comment by mcadam** [comment]
Any updates on that one? 0.7.0 is not working :(

**Comment by huangsuyu** [comment]
Hello, @mcadam  @hickwa 

Please note that the binaries are stored with `git lfs`

You have to download the whole file
