### ISSUE TITLE
Wrong apphash on 7.2

### ISSUE THREAD

**Issue by slimm609** [binance-chain/node-binary#223]
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected E3ED6775754CAEF4830AD7EEA1381807BAC6C02B1B5FFC354BA233EA2C5A4FD2, got A0998B21BD632A347F64A42B552BCA172D7005EAE8BEDFEBD6FE9C90BFBDC036

We are getting this error on multiple binance nodes.    They all fail at the same point.      I copied the latest app.toml and genesis from `https://github.com/binance-chain/node-binary/tree/master/fullnode/prod/0.7.2/config`.    

I also did a state_recover back to 99549999 to let it sync back up and it hit the same error.   99817571 is the latest block I am able to see that it has synced.

**Comment by huangsuyu** [comment]
Hello, @slimm609 

Could you please check open file limits of your machines?

```
ulimit -a
```

It's recommended to set the threshold to 65535. 

You can revert to 99817570 and restart. The commands are here: https://docs.binance.org/fullnodeissue.html#forget-to-upgrade

**Comment by abyssal0** [comment]
Hello,   @slimm609
How did you solve it? I met the same problem at block 99746527.

**Comment by slimm609** [comment]
I got it working on 1 machine by doing a state_recover to the rounded nearest 10k block and then restarting the chain, it took reseting it 2 times before it got past the issue

**Comment by abyssal0** [comment]
It still doesn't work. 99746527 is the latest block I am able to see that it has synced.

**Comment by abyssal0** [comment]
@slimm609   I've tried more than five times and still haven't past the issue

**Comment by slimm609** [comment]
I don’t have access to a binance node anymore to even troubleshoot it, sorry

**Comment by slimm609** [comment]
Did you update your configs to include the new upgrades

**Comment by abyssal0** [comment]
I updated it, otherwise it wouldn't have gone from 99550000 to 99746527

**Comment by abyssal0** [comment]
I updated configs again and started to sync again.The problem has been solved temporarily. I hope it won't happen again after synchronizing some blocks.

**Comment by huangsuyu** [comment]
Going to close this, as the issue should be solved now for you

Please reopen when necessory
