### ISSUE TITLE
panic: Failed to process committed block (99746528)

### ISSUE THREAD

**Issue by abyssal0** [binance-chain/node-binary#224]
panic: Failed to process committed block (99746528:CB3C76C6A6638F5EEC2C44B375C2299F019086C6C3FC2474FBA3D79B163268DE): Wrong Block.Header.AppHash.  Expected 350B6CBCBC4D028F90673724E1950B4AB6E64132C9A403B3BD23F4C4735325C1, got 778570E6BCCCAB6A3670AF0A0C53D953735953A3EE028A89E47AE39ECC90D9D9

**Comment by abyssal0** [comment]
panic: Failed to process committed block (99746528:CB3C76C6A6638F5EEC2C44B375C2299F019086C6C3FC2474FBA3D79B163268DE): Wrong Block.Header.AppHash.  Expected 350B6CBCBC4D028F90673724E1950B4AB6E64132C9A403B3BD23F4C4735325C1, got 778570E6BCCCAB6A3670AF0A0C53D953735953A3EE028A89E47AE39ECC90D9D9

goroutine 455363 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0009161a0)
        /Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:399 +0x18cc
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /Users/huangsuyu/go/pkg/mod/github.com/binance-chain/bnc-tendermint@v0.32.3-binance.1/blockchain/v0/reactor.go:126 +0x84

**Comment by abyssal0** [comment]
I also did a state_recover back to let it sync back up and it hit the same error. 99746527 is the latest block I am able to see that it has synced.

**Comment by huangsuyu** [comment]
Hello, @abyssal0 

Please try 
```
state_recove 99746526 {home-path}
```

This will revert to the block before crash and restart again.

**Comment by abyssal0** [comment]
@huangsuyu I try meny times. not work!

**Comment by abyssal0** [comment]
@huangsuyu  I know all the methods you mentioned and have tried many times, but it doesn't solve the problem

**Comment by abyssal0** [comment]
I updated configs again and started to sync again.The problem has been solved temporarily. I hope it won't happen again after synchronizing some blocks.
Last update went from 99550000 to 99746527. Hope there will be no more problems this time.

**Comment by DevMinJong** [comment]
Did you solve the issue?
