### ISSUE TITLE
panic: Failed to process committed block

### ISSUE THREAD

**Issue by Cren700** [binance-chain/node-binary#24]
> /node-binary/fullnode/testnet/0.5.8/linux/bnbchaind start --home /root/.bnbchaind/ --pruning breathe &

> panic: Failed to process committed block (2:41B358BC3AECCD5957414DB4AB435E844E65474CA9B01732F9F81CF7A6665FF9): Wrong Block.Header.AppHash.  Expected FAF374AC293B4CF88C1BF49499A425C0B348A3106287CDAC599CB7A79CAB0811, got 985E9C7761374CF2448E82CEA2CE4954302DB3AF94829A6DFD9982B2ED9CBA75

>goroutine 171 [running]:
>github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000a99a00)
	/bnchome/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:375 +0x1c1c
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/bnchome/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x89

> [1]+  Exit 2                  /node-binary/fullnode/testnet/0.5.8/linux/bnbchaind start --home /root/.bnbchaind/ --pruning breathe

**Comment by ackratos** [comment]
I think you have resolved this offline right? Does your state sync against tesetnet work now?

**Comment by huangsuyu** [comment]
> > /node-binary/fullnode/testnet/0.5.8/linux/bnbchaind start --home /root/.bnbchaind/ --pruning breathe &
> 
> > panic: Failed to process committed block (2:41B358BC3AECCD5957414DB4AB435E844E65474CA9B01732F9F81CF7A6665FF9): Wrong Block.Header.AppHash.  Expected FAF374AC293B4CF88C1BF49499A425C0B348A3106287CDAC599CB7A79CAB0811, got 985E9C7761374CF2448E82CEA2CE4954302DB3AF94829A6DFD9982B2ED9CBA75
> 
> > goroutine 171 [running]:
> > github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000a99a00)
> > /bnchome/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:375 +0x1c1c
> > created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
> > /bnchome/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x89
> 
> > [1]+  Exit 2                  /node-binary/fullnode/testnet/0.5.8/linux/bnbchaind start --home /root/.bnbchaind/ --pruning breathe

please make sure that you have downloaded the correct genesis file

**Comment by ackratos** [comment]
resolved offline
