### ISSUE TITLE
Support `timeRelock` with same as original locked amount

### ISSUE THREAD

**Issue by roy1210** [binance-chain/node-binary#254]
Hi team!

I'm using [JS SDK](https://github.com/binance-chain/javascript-sdk) in my project. 
I'd like to run `timeRelock`function with the `amount` which same as original locked amount. But unfortunately, API returns `Error: Invalid lock amount: new locked coin xxx should be more than original locked coin`.

I think it makes more sense to let user allow`timeRelock` with **same as original** or more than the original amount. 
Would you help to consider that allow to proceed `timeRelock` with the same amount?  
If you could that would be much appreciated!!

![Screenshot 2020-09-23 at 8 27 13 PM](https://user-images.githubusercontent.com/42575132/94016664-fac5f380-fde0-11ea-9ebf-f4432f3ac24f.png)

**Comment by huangsuyu** [comment]
have you extended the timelock span?

**Comment by roy1210** [comment]
Yes I did extend the lock span.

**Comment by roy1210** [comment]
Hi @huangsuyu 
Any update for this??
I do have an extended lock period, hence I think it is a bug in API responses.![image](https://user-images.githubusercontent.com/42575132/94399643-58b85980-019a-11eb-8440-2e4bcba422a3.jpeg)

**Comment by yutianwu** [comment]
@roy1210  if you don't want to increase the lock amount, just set it to 0, so the amount will not be updated

**Comment by roy1210** [comment]
Hi @yutianwu 
Thank you for your reply!!
I tried amount with "0", but API returns `input number should be a positive number ` error. 
Please help to advise.

```
{denom: "BNB", amount: "0"}
``` 

![200929 Error](https://user-images.githubusercontent.com/42575132/94462559-49fb9200-01ee-11eb-9e6b-fbffce5615d2.jpg)

**Comment by roy1210** [comment]
@yutianwu 
I think this error due to JS SDK... Could you help to modify this line/logic ?
https://github.com/binance-chain/javascript-sdk/blob/ac5a108a81b55ca0cd034b5ca352fc1c22093aa1/src/utils/validateHelper.ts#L13

**Comment by roy1210** [comment]
@yutianwu 
By the way, I'm using using specific version of @binance-chain/javascript-sdk version 3.0.2 because version ^4 will get another error in my environment.

**Comment by huangsuyu** [comment]
@roy1210 maybe you need to set it to nil

**Comment by roy1210** [comment]
@huangsuyu 
Do you mean like this?

{denom: "BNB", amount: null}

**Comment by yutianwu** [comment]
sorry, can u retry with {} instead of {denom: "BNB", amount: 0}

**Comment by roy1210** [comment]
You mean like this. (Hopefully JS accepts a blank object...
I will check it this noon.

amount = {}

**Comment by roy1210** [comment]
@yutianwu 
I tried following 2 cases. Unfortunately, JS SDK returns error...

1. `amount = [{}]`  => [big.js] Invalid number
2. `amount = {}`  =>  TypeError: coins.forEach is not a function

<img width="807" alt="Screenshot 2020-09-30 at 12 09 17 PM" src="https://user-images.githubusercontent.com/42575132/94642287-46632a80-0316-11eb-9afc-69e16db114fd.png">
<img width="678" alt="Screenshot 2020-09-30 at 12 10 50 PM" src="https://user-images.githubusercontent.com/42575132/94642295-4b27de80-0316-11eb-919f-dfdcd72e226b.png">

**Comment by huangsuyu** [comment]
Hello, @roy1210 

I have tested with `bnbcli` and there was no issue with `relock`. The problem can be within the implementation of js-sdk. Please raise an issue in that repo. And the devs can take a look later.

**Comment by roy1210** [comment]
@huangsuyu @yutianwu 

Noted, thank you for your help.
Could you advise what 'amount' (to be relock same amount as original locked) is no issue of 'relock' via bnbcli?

**Comment by roy1210** [comment]
Hi @huangsuyu @yutianwu

I have forked JavaScript-SDK and removed validation of the 0 amount check. But the node still blocks my tx. (Perhaps it is the msg validate function failing?)
Would you mind checking below screenshot which I tried 4 patterns to `relock` same amount as `locked`? 
Your reply is much appreciated!

![image](https://user-images.githubusercontent.com/42575132/95222739-65d4e880-082b-11eb-8fb3-20dbc402d3da.png)

![image](https://user-images.githubusercontent.com/42575132/95222773-6d948d00-082b-11eb-956e-e2d18eab3927.png)

**Comment by roy1210** [comment]
Hi @huangsuyu @yutianwu

Any update for above my questions? Your reply is much appreciated!!

**Comment by yutianwu** [comment]
the last one is expected, but it seems the signature is not right, it should be related to the codec. You can try go-sdk if you want to verify the encoded bytes.

**Comment by yutianwu** [comment]
btw, why do you use [{}] instead of []

**Comment by roy1210** [comment]
Hi @yutianwu 
Thank you for your reply.
> btw, why do you use [{}] instead of []

I just tried with `[]`. But API return same error `Error: signature verification failed
`

![image](https://user-images.githubusercontent.com/42575132/95536434-a3996300-0a1d-11eb-87ef-79903a36d58a.png)

**Comment by roy1210** [comment]
> but it seems the signature is not righ
API return 200 if amount is 1,000satoshi more than original locked value. Thus, I think it is the bug with node in somewhere...

**Comment by yutianwu** [comment]
can you try with go-sdk, I am not familiar with the js-sdk

**Comment by roy1210** [comment]
Hi @yutianwu 

Yes, `const  amount=[]` should be working!
I have forked the JS SDK and changed as below, then now `relock` with same amount is worked!! 
Thank you for your help!

![image](https://user-images.githubusercontent.com/42575132/95651521-906dbc80-0b1d-11eb-98ea-460b4a71e4b6.png)
