### ISSUE TITLE
Post staking rewards

### ISSUE THREAD

**Issue by atomical** [binance-chain/node-binary#268]
After staking on BSC how can one see the rewards? I don't see a way to do it with the client. Both viewing and claiming.

**Comment by huangsuyu** [comment]
You can query rewards with this API

https://api.binance.org/v1/staking/chains/bsc/delegators/{delegator}/rewards

**Comment by atomical** [comment]
Thanks @huangsuyu! This is most helpful. I tipped you a few BAT.
