### ISSUE TITLE
Can't query account

### ISSUE THREAD

**Issue by jchung00** [binance-chain/node-binary#27]
Followed the docs to generate new keys. Then, I tried to query the account, but I get an error that the account wasn't found in the state. This isn't surprising because the keys are generated and stored locally, and there was no way for the chain to know that this account was created... But how do I solve this problem?
```
./client.sh keys add newkey
Enter a passphrase for your key:
Repeat the passphrase:
NAME:	TYPE:	ADDRESS:						PUBKEY:
newkey	local	bnb17qgkcvzjagtcqvs3wj9srd8tz2j2hnsg5me0jf	bnbp1addwnpepqgqvkq2mpc7sgertw2res3487ljwh3egwh656fhkg3kpgwww3saqytkexqw
**Important** write this seed phrase in a safe place.
It is the only way to recover your account if you ever forget your password.
```

```./client.sh account bnb17qgkcvzjagtcqvs3wj9srd8tz2j2hnsg5me0jf --trust-node --chain-id Binance-Chain-Tigris --node https://dataseed5.defibit.io:443
ERROR: No account with address bnb17qgkcvzjagtcqvs3wj9srd8tz2j2hnsg5me0jf was found in the state.
Are you sure there has been a transaction involving it?```

**Comment by ackratos** [comment]
You must used bnbcli account command which can only query account that has already on chain (which means the account has been involved into a transaction I.e. a destination of transfer)

To list local stored account you can use ‘bnbcli keys list’

**Comment by jchung00** [comment]
Okay, so an account on chain has to send BNB tokens to this one before the account is actually on the chain?

**Comment by ackratos** [comment]
Yes
