### ISSUE TITLE
latest release AppHash error after state recover

### ISSUE THREAD

**Issue by jblanchette-circle** [binance-chain/node-binary#271]
Using latest `0.8.2` release and doing a state recover at -1 block before last hard fork `146059999` does not fix node

Expected behavior:

state recover tool allows node to progress past hard fork block

Actual beahvior:

node logs this and loops on block range before fork

```
ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 50753935CF80ACF099D5555A7A239C2A88E2B08CE45605265C523F237ACB4116, got EADDD011CB32EE5A7129F1578CAC90DB1D565EBDCFA2E7F96F29B2FCD36955C2
```

**Comment by huangsuyu** [comment]
Can you please try to revert 146050000 and restart again?

**Comment by jblanchette-circle** [comment]
Using state recover at height `146050000` fixed our issues.  Thank you for the quick help @huangsuyu

**Comment by jblanchette-circle** [comment]
ah sorry I closed too early maybe @huangsuyu 

we see a new panic error when processing the next block after the hard fork

```
panic: Failed to process committed block (146060001:005749E058B7EB6183775B5E1E2610C3D49A13E7E60C48254CF4ECAB90DD44B9): Wrong Block.Header.AppHash.  Expected 50753935CF80ACF099D5555A7A239C2A88E2B08CE45605265C523F237ACB4116, got EADDD011CB32EE5A7129F1578CAC90DB1D565EBDCFA2E7F96F29B2FCD36955C2
```

**Comment by huangsuyu** [comment]
> ah sorry I closed too early maybe @huangsuyu
> 
> we see a new panic error when processing the next block after the hard fork
> 
> ```
> panic: Failed to process committed block (146060001:005749E058B7EB6183775B5E1E2610C3D49A13E7E60C48254CF4ECAB90DD44B9): Wrong Block.Header.AppHash.  Expected 50753935CF80ACF099D5555A7A239C2A88E2B08CE45605265C523F237ACB4116, got EADDD011CB32EE5A7129F1578CAC90DB1D565EBDCFA2E7F96F29B2FCD36955C2
> ```

did you update `app.toml`?

**Comment by Crypto2** [comment]
I'm having issues too on 0.8.2 trying to restore from the Feb snapshot at https://docs.binance.org/guides/node/snapshot.html
It works for a bit then starts crashing with:

panic: Failed to process committed block (146914713:CEC249A742F59B0E3A722339E5B696E14CDB2889800C09229A1D74317C279903): Wrong Block.Header.AppHash.  Expected 5F37835A

I did update app.toml/config.toml/genesis.toml as well yes.

**Comment by jblanchette-circle** [comment]
@huangsuyu hi yes we have an updated `app.toml`

here is the raw config file with non-relevant parts snipped out

please let me know if this is being addressed as it is causing significant downtime

```

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

[base]
# Interval blocks of breathe block, if breatheBlockInterval is 0, breathe block will be created every day.
breatheBlockInterval = 0
# Size of account cache
accountCacheSize = 30000
# Size of signature cache
signatureCacheSize = 30000
# Running mode when start up, 0: Normal, 1: TransferOnly, 2: RecoverOnly
startMode = 0
# Concurrency of OrderKeeper, should be power of 2
orderKeeperConcurrency = 2
# Days count back for breathe block
breatheBlockDaysCountBack = 7

[upgrade]
# Block height of BEP6 upgrade
BEP6Height = 20300000
# Block height of BEP9 upgrade
BEP9Height = 20300000
# Block height of BEP10 upgrade
BEP10Height = 20300000
# Block height of BEP19 upgrade
BEP19Height = 20300000
# Block height of BEP12 upgrade
BEP12Height = 25120000
# Block height of BEP3 upgrade
BEP3Height = 41277000
# Block height of FixSignBytesOverflow upgrade
FixSignBytesOverflowHeight = 51467800
# Block height of LotSizeOptimization upgrade
LotSizeUpgradeHeight = 51467800
# Block height of changing listing rule upgrade
ListingRuleUpgradeHeight = 51467800
# Block height of FixZeroBalanceHeight upgrade
FixZeroBalanceHeight = 51467800
# Block height of BEP8 upgrade
BEP8Height = 99550000
# Block height of BEP67 upgrade
BEP67Height = 99550000
# Block height of BEP70 upgrade
BEP70Height = 99550000
# Block height of smart chain upgrade
LaunchBscUpgradeHeight = 109999000
# Block height of BEP82Height upgrade
BEP82Height = 146060000
# Block height of BEP84Height upgrade
BEP84Height = 146060000
# Block height of BEP87Height upgrade
BEP87Height = 146060000
# Block height of FixFailAckPackage upgrade
FixFailAckPackageHeight = 146060000
# Block height of Enable Account Scripts For CrossChain Transfer upgrade
EnableAccountScriptsForCrossChainTransferHeight = 146060000

[addr]
# Bech32PrefixAccAddr defines the Bech32 prefix of an account's address
bech32PrefixAccAddr = "bnb"
# Bech32PrefixAccPub defines the Bech32 prefix of an account's public key
bech32PrefixAccPub = "bnbp"
# Bech32PrefixValAddr defines the Bech32 prefix of a validator's operator address
bech32PrefixValAddr = "bva"
# Bech32PrefixValPub defines the Bech32 prefix of a validator's operator public key
bech32PrefixValPub = "bvap"
# Bech32PrefixConsAddr defines the Bech32 prefix of a consensus node address
bech32PrefixConsAddr = "bca"
# Bech32PrefixConsPub defines the Bech32 prefix of a consensus node public key
bech32PrefixConsPub = "bcap"

##### publication related configurations #####
[publication]
# configurations ends with Kafka can be a semi-colon separated host-port list
# Whether we want publish market data (this includes trades and order)
publishOrderUpdates = true
orderUpdatesTopic = "orders"
orderUpdatesKafka = "127.0.0.1:9092"

... SNIPPED ..

```

**Comment by jblanchette-circle** [comment]
@huangsuyu just bumping again in case you could help?

we may be able to sync the chain from scratch as a work around but `state_sync_height` seems to be ignored when set to the last hard fork height

**Comment by huangsuyu** [comment]
> @huangsuyu just bumping again in case you could help?
> 
> we may be able to sync the chain from scratch as a work around but `state_sync_height` seems to be ignored when set to the last hard fork height

you can set `state_sync_height`  to the latest value. https://explorer.binance.org/block/147742261

**Comment by jblanchette-circle** [comment]
Is there a way to state recover back to the hard fork block?  Is there
maybe an issue with a plug-in or other change in the new version?

**Comment by huangsuyu** [comment]
@jblanchette-circle I will find the height soon. 

BTW, could you please check if your node is not crashed due to open file limit restriction?

**Comment by johnmathews** [comment]
We have this issue also.

**Comment by jblanchette-circle** [comment]
@huangsuyu confirmed node not crashed due to open file limits

am happy to setup contact on telegram or other channels to sort this out - if possible can we escalate the priority?

**Comment by johnmathews** [comment]
I started fresh and instead of using the `install.sh` script I did the "manual install" and it's synced. no problems as far as i can tell. 
thanks for offering to help though :)

**Comment by jblanchette-circle** [comment]
we are able to manually sync but we need to sync from the last hard fork block.  the historical block information is needed for the wallet system

**Comment by jblanchette-circle** [comment]
@huangsuyu any updates on a height we can state recover from?   in the past there have been hotfix releases made to address this, could we go that route?

nearing on two weeks since the hard fork worth of downtime

**Comment by zaryabshakir** [comment]
@huangsuyu getting same issue with BNB node version 0.8.2 ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash, Im running full node with docker please help how to fix this issue properly so node start working Thanks

**Comment by zaryabshakir** [comment]
Hi @huangsuyu any update please

**Comment by jblanchette-circle** [comment]
We were able to solve this by syncing a fully updated node to a clean snapshot from before the latest hard fork and ensuring the file maximum limits were not being reached.

Closing as this workaround got us past the state recovery issue
