### ISSUE TITLE
BNBCLI: unable to stake using Ledger

### ISSUE THREAD

**Issue by jkmbnb** [binance-chain/node-binary#274]
Hi I am using latest version for BNBCLI 0.8.2 on Linux.
I have added keys for Ledger as "bnbcli keys add testLedger --ledger --index 0 --account 0"
When I am trying to delegate using the following command:
bnbcli staking bsc-delegate --chain-id Binance-Chain-Tigris --side-chain-id bsc --from testLedger --validator bva1tfh30c67mkzfz06as2hk0756mgdx8mgypqldvm --amount 100000000:BNB --home ~/home_cli

I am getting error Key not defined. Any idea if I am missing anything here?

**Comment by huangsuyu** [comment]
please try without ` --home ~/home_cli`

**Comment by jkmbnb** [comment]
Tried not working,  Can you please share a sample command to delegate using ledger and bnbcli.

**Comment by jkmbnb** [comment]
What should be the value for chain-id

**Comment by jkmbnb** [comment]
I am getting the error as:
./bnbcli staking bsc-delegate --chain-id Binance-Chain-Tigris --side-chain-id bsc --from=test --validator bva13le7wtdw3kttw0cp30pprq049esmndvdsavysq --amount 100000000:BNB

ERROR: ABCIQuery: Post http://localhost:26657: dial tcp 127.0.0.1:26657: connect: connection refused

**Comment by jkmbnb** [comment]
How/what is the command to use public node? such as https://dataseed1.binance.org:443

**Comment by jkmbnb** [comment]
I am able to stake by specifying --node 
Thanks for the help.
