### ISSUE TITLE
Full node binary

### ISSUE THREAD

**Issue by cgebe** [binance-chain/node-binary#3]
When will the full node binary be available? I can see the doc already.

**Comment by thosuperman** [comment]
I'm waiting for **full node binary** also.

**Comment by thosuperman** [comment]
@yutianwu

**Comment by yutianwu** [comment]
coming soon, just stay tuned :)

**Comment by thosuperman** [comment]
We're still waiting for **full node binary** @yutianwu

**Comment by Mourad-R** [comment]
same here :)

**Comment by darren-liu** [comment]
it is there already.
