### ISSUE TITLE
Require an updated documentation.

### ISSUE THREAD

**Issue by saarang1995** [binance-chain/node-binary#37]
Hello Team,

I am setting up the Light Client Node by following this documentation :
"https://docs.binance.org/light-client.html"
It seems like the github repo has been updated but not the documentation. I am facing a lot of difficulties because of this.

Could you please let me know how to find the updated documentation if it exists or when it will be released.

I am going through the documentation because I couldn't figure out how to change the default port (27147) of the node. It is by default pointing to localhost and I want to set it to 0.0.0.0.

**Comment by huangsuyu** [comment]
Hello, @saarang1995 

Please take a look at the latest doc on light client: https://docs.binance.org/light-client.html

Thanks
