### ISSUE TITLE
Mintable True error with Ledger

### ISSUE THREAD

**Issue by jpthor** [binance-chain/node-binary#45]
## Ledger Bug

When setting "mintable=false" in the CLI using Ledger, the Ledger overrides this to "mintable=true". 

I believe this is a bug in the node-binary and how it serialises the transaction *before* it sends it to the ledger, so the issue is raised here, not in the [Ledger Repo](https://github.com/binance-chain/ledger-app-binance). 

## Set up

Use the CLI to create a token issuance with mintable=false:

![image](https://user-images.githubusercontent.com/41815753/57828413-c4409780-77ee-11e9-82ae-ca8025ff05de.png)

Use the ledger to send the transaction. The Ledger over-rides this, and sets it to true:

![image](https://user-images.githubusercontent.com/41815753/57828401-b7bc3f00-77ee-11e9-9fc3-bb4483bf7fe2.png)

## Workaround
Delete "--mintable false" from the CLI command and the ledger chooses the default, which is false and an asset can be issued that is mintable=false.

**Comment by notatestuser** [comment]
Thanks for the report! This one has been fixed in #44. (tl;dr: Use `--mintable=false` or omit the flag completely in your CLI invocation.)
