### ISSUE TITLE
Blockpool has no peers

### ISSUE THREAD

**Issue by DreamXzxy** [binance-chain/node-binary#46]
I want to follow the guide as https://docs.binance.org/fullnodeissue.html run the full node, but when i start my node, i find the height is always 0. so i check the bnc.log, the error like the 
 shown below
![image](https://user-images.githubusercontent.com/17998878/57840811-ebea2c80-77fb-11e9-8bdd-010a8bcbb212.png)

**Comment by huangsuyu** [comment]
This is a connection stability issue. and have been solved.
