### ISSUE TITLE
请问如何对块data数据txs进行解码呢

### ISSUE THREAD

**Issue by singpenguin** [binance-chain/node-binary#49]
请问如何对块data数据txs进行解码呢，go-sdk和python-sdk都没有单独方法解码，也没有文档说明，应该如何操作呢？

**Comment by zhangyanhuivv** [comment]
先base64解码  再sha256

**Comment by singpenguin** [comment]
sha256不是单向的吗，有点懵

**Comment by singpenguin** [comment]
@zhangyanhuivv 是不是要借助别的库进行解码啊

**Comment by singpenguin** [comment]
懂了，这个解出来只是个txid，不包含交易内容。^_^
