### ISSUE TITLE
How to decode the data in transaction?

### ISSUE THREAD

**Issue by freddieee** [binance-chain/node-binary#53]
Hi, I noticed in the docs that the data in tx is encoded in Amino logic. Is there any handy tool or library to decode these content? Appreciate for any insights : )

**Comment by ruslansalikhov** [comment]
example in golang

```
package main

import (
    "encoding/json"
    "fmt"
    "github.com/binance-chain/go-sdk/client/rpc"
    ctypes "github.com/binance-chain/go-sdk/common/types"
    "github.com/binance-chain/go-sdk/types"
    "github.com/binance-chain/go-sdk/types/tx"
)

func main() {
    nodeAddr := "tcp://127.0.0.1:27147"
    client := rpc.NewRPCClient(nodeAddr, ctypes.ProdNetwork)

    codec := types.NewCodec()

    number := int64(8095579)
    //number := int64(8643229)
    res, _ := client.Block(&number)
    txs := res.Block.Data.Txs

    parsedTxs := make([]tx.StdTx, len(txs))
    for i := range txs {
        err := codec.UnmarshalBinaryLengthPrefixed(txs[i], &parsedTxs[i])
        if err != nil {
            fmt.Println("Error - codec unmarshal")
            return
        }
    }

    bz, err := json.Marshal(parsedTxs)

    if err != nil {
       fmt.Println("Error - json marshal")
       return
    }

    fmt.Println(string(bz))
}
```

**Comment by huangsuyu** [comment]
There  are some examples:  https://old-community.binance.org/t/bnb-api-integration/3020

**Comment by freddieee** [comment]
thanks @huangsuyu , @ruslansalikhov ! Both of yours are very helpful to me!

**Comment by amjadDev** [comment]
hello @ruslansalikhov   i am done with this issue  using  go language except transaction has can you guide me what method i need u use for transaction id like
17E6A0811811B75BB94FA8955295D7E2B5D9DA05E6A092685EA946D42E03614C
refrence 
https://explorer.binance.org/tx/17E6A0811811B75BB94FA8955295D7E2B5D9DA05E6A092685EA946D42E03614C
 Code:


var ParseAminoTx = func(w http.ResponseWriter, r * http.Request) {

        codec: = types.NewCodec()
        decodetx64,
        err: = base64.StdEncoding.DecodeString("yAHwYl3uClAqLIf6CiQKFP6aa5bCfSjIPBZs4zrEml5FE+ISEgwKA0JOQhCem7a3ggESJAoU/imIh6AV6Ub6fhN01DL9AChX0cISDAoDQk5CEJ6btreCARJwCibrWumHIQOlVsK2sHBzehAuYoMcln0SdKFG6Ud5NZpkiv/jcUJRSxJAP66nAeKx/671oBzc37WRnxxXCOxmIJOdCCZEEeSxiv1ualjMoI7sKDiZoTHzS6e1mpjqIa2MHYEM/Tq99+BfCRjC1wEgTQ==")

        if err != nil {
                fmt.Println("error:", err)
        }

        txs: = [] string {
                string(decodetx64)
        }

                parsedTxs: = make([] tx.StdTx, len(txs))
        for i: = range txs {
                err: = codec.UnmarshalBinaryLengthPrefixed([] byte(txs[i]), & parsedTxs[i])

                if err != nil {
                        fmt.Println("Error - codec unmarshal")
                }
        }

                bz,
        err: = json.Marshal(parsedTxs)

        if err != nil {
                fmt.Println("Error - json marshal")

        }
        u.Respond(w, u.Message(true, string(bz)))

}

output

{"message":"[{\"msg\":[{\"inputs\":[{\"address\":\"bnb1l6dxh9kz055vs0qkdn3n43y6tez38csj4q7x5d\",\"coins\":[{\"denom\":\"BNB\",\"amount\":35012840862}]}],\"outputs\":[{\"address\":\"bnb1lc5c3paqzh55d7n7zd6dgvhaqq5905wzr849tj\",\"coins\":[{\"denom\":\"BNB\",\"amount\":35012840862}]}]}],\"signatures\":[{\"pub_key\":[3,165,86,194,182,176,112,115,122,16,46,98,131,28,150,125,18,116,161,70,233,71,121,53,154,100,138,255,227,113,66,81,75],\"signature\":\"P66nAeKx/671oBzc37WRnxxXCOxmIJOdCCZEEeSxiv1ualjMoI7sKDiZoTHzS6e1mpjqIa2MHYEM/Tq99+BfCQ==\",\"account_number\":27586,\"sequence\":77}],\"memo\":\"\",\"source\":0,\"data\":null}]","status":true}

**Comment by huangsuyu** [comment]
Hello, @amjadDev 

tx hash is sha256(decodetx64).
you can use ` parsedTxs[i].Hash()`

**Comment by amjadDev** [comment]
> Hello, @amjadDev
> you can use ` parsedTxs[i].Hash()`

i tired got this error
parsedTxs[i].Hash undefined (type tx.StdTx has no field or method Hash)
m missing any function or package?

**Comment by amjadDev** [comment]
> > Hello, @amjadDev
> > you can use ` parsedTxs[i].Hash()`
> 
> i tired got this error
> parsedTxs[i].Hash undefined (type tx.StdTx has no field or method Hash)
> m missing any function or package?

thanks !!

sorted  

decodetx64, err := base64.StdEncoding.DecodeString("ygHwYl3uClAqLIf6CiQKFJGTdSD0BFj1tBTSZ5YbRsGXid1wEgwKA0JOQhCAmpGy9gISJAoUNZyodQE2lvxtwuhMFhar4FgLeWESDAoDQk5CEICakbL2AhJwCibrWumHIQNW4KWAOJpv0syRzVJcbVpNgFSvcN8XSE5YZ4+fV0oLTRJAmEC1SzRLFtH+xCE/0ajwJGYaLw4AqdoMqZHVQlxc1rQHCsnkC8/qYTKKd+MZvPmhRfvp12fSRf93olACfFnLwxgzIPmDBSAC")
        sha256 := sha256.Sum256([]byte(decodetx64))
        fmt.Printf("%x\n", sha256)

this is working for me.

**Comment by blockmonk** [comment]
> Hello, @amjadDev
> you can use ` parsedTxs[i].Hash()`

@huangsuyu I am trying to get transaction data from data_hash

"data_hash": "A7044A2430D5F4F461A59E1634F4739B1128912946424A207A73F27B7FCA1C29",

what decryption should i need to use. here is my block result

 "block_id": {
                    "hash": "09F845024BD5313129374DE2ED8F187A1F21373580178A7E18BF8D6352E133F3",
                    "parts": {
                        "total": "1",
                        "hash": "E6995EC7B04C8D5F686AE0C0AD92C189445B9A975600B3166B243573D059D548"
                    }
                },
                "header": {
                    "version": {
                        "block": "10",
                        "app": "0"
                    },
                    "chain_id": "Binance-Chain-Tigris",
                    "height": "21993735",
                    "time": "2019-07-22T15:48:10.041358386Z",
                    "num_txs": "2",
                    "total_txs": "6132889",
                    "last_block_id": {
                        "hash": "2EF6A9B6BA8AD1CBF5E7C382906C9CBECD5958143CB9C185EA0235541015482E",
                        "parts": {
                            "total": "1",
                            "hash": "4C9D00EC8E5EABD25482BD49CBE89A0AA8D435514C8202F119087A9E471EF0B0"
                        }
                    },
                    "last_commit_hash": "5BBAB5A23DC5E69360EBF8697A011A68CD277061ECB66216DD5CC54B7E26C75D",
                    "data_hash": "A7044A2430D5F4F461A59E1634F4739B1128912946424A207A73F27B7FCA1C29",
                    "validators_hash": "43C53A50D8653EF8CF1E5716DA68120FB51B636DC6D111EC3277B098ECD42D49",
                    "next_validators_hash": "43C53A50D8653EF8CF1E5716DA68120FB51B636DC6D111EC3277B098ECD42D49",
                    "consensus_hash": "294D8FBD0B94B767A7EBA9840F299A3586DA7FE6B5DEAD3B7EECBA193C400F93",
                    "app_hash": "B30FE7AACEADCB5AAD748CB3088AD3530BC21FB5205C06A242A14ACDB62ECEFC",
                    "last_results_hash": "",
                    "evidence_hash": "",
                    "proposer_address": "3CD4AABABDDEB7ABFEA9618732E331077A861D2B"
                }

**Comment by guoshijiang** [comment]
How to decode txs use python?

**Comment by oom-tesla** [comment]
> example in golang
> 
> ```
> package main
> 
> import (
>     "encoding/json"
>     "fmt"
>     "github.com/binance-chain/go-sdk/client/rpc"
>     ctypes "github.com/binance-chain/go-sdk/common/types"
>     "github.com/binance-chain/go-sdk/types"
>     "github.com/binance-chain/go-sdk/types/tx"
> )
> 
> func main() {
>     nodeAddr := "tcp://127.0.0.1:27147"
>     client := rpc.NewRPCClient(nodeAddr, ctypes.ProdNetwork)
> 
>     codec := types.NewCodec()
> 
>     number := int64(8095579)
>     //number := int64(8643229)
>     res, _ := client.Block(&number)
>     txs := res.Block.Data.Txs
> 
>     parsedTxs := make([]tx.StdTx, len(txs))
>     for i := range txs {
>         err := codec.UnmarshalBinaryLengthPrefixed(txs[i], &parsedTxs[i])
>         if err != nil {
>             fmt.Println("Error - codec unmarshal")
>             return
>         }
>     }
> 
>     bz, err := json.Marshal(parsedTxs)
> 
>     if err != nil {
>        fmt.Println("Error - json marshal")
>        return
>     }
> 
>     fmt.Println(string(bz))
> }
> ```

Hi @ruslansalikhov Do you have example in Node Js?

**Comment by oom-tesla** [comment]
> > > Hello, @amjadDev
> > > you can use ` parsedTxs[i].Hash()`
> > 
> > 
> > i tired got this error
> > parsedTxs[i].Hash undefined (type tx.StdTx has no field or method Hash)
> > m missing any function or package?
> 
> thanks !!
> 
> sorted
> 
> decodetx64, err := base64.StdEncoding.DecodeString("ygHwYl3uClAqLIf6CiQKFJGTdSD0BFj1tBTSZ5YbRsGXid1wEgwKA0JOQhCAmpGy9gISJAoUNZyodQE2lvxtwuhMFhar4FgLeWESDAoDQk5CEICakbL2AhJwCibrWumHIQNW4KWAOJpv0syRzVJcbVpNgFSvcN8XSE5YZ4+fV0oLTRJAmEC1SzRLFtH+xCE/0ajwJGYaLw4AqdoMqZHVQlxc1rQHCsnkC8/qYTKKd+MZvPmhRfvp12fSRf93olACfFnLwxgzIPmDBSAC")
> sha256 := sha256.Sum256([]byte(decodetx64))
> fmt.Printf("%x\n", sha256)
> 
> this is working for me.

Hi @amjadDev I need to get transaction hash as well using Node JS If you can guide me how to do it would be very helpful.

**Comment by 0xsalah** [comment]
> example in golang
> 
> ```
> package main
> 
> import (
>     "encoding/json"
>     "fmt"
>     "github.com/binance-chain/go-sdk/client/rpc"
>     ctypes "github.com/binance-chain/go-sdk/common/types"
>     "github.com/binance-chain/go-sdk/types"
>     "github.com/binance-chain/go-sdk/types/tx"
> )
> 
> func main() {
>     nodeAddr := "tcp://127.0.0.1:27147"
>     client := rpc.NewRPCClient(nodeAddr, ctypes.ProdNetwork)
> 
>     codec := types.NewCodec()
> 
>     number := int64(8095579)
>     //number := int64(8643229)
>     res, _ := client.Block(&number)
>     txs := res.Block.Data.Txs
> 
>     parsedTxs := make([]tx.StdTx, len(txs))
>     for i := range txs {
>         err := codec.UnmarshalBinaryLengthPrefixed(txs[i], &parsedTxs[i])
>         if err != nil {
>             fmt.Println("Error - codec unmarshal")
>             return
>         }
>     }
> 
>     bz, err := json.Marshal(parsedTxs)
> 
>     if err != nil {
>        fmt.Println("Error - json marshal")
>        return
>     }
> 
>     fmt.Println(string(bz))
> }
> ```

Hi, I'm using the example of @ruslansalikhov and I'm getting the following error:

`Error - codec unmarshal unmarshal to tx.StdTx failed after 100 bytes (error reading array contents: expected field number: 1; got: 4): 0A5A166E681B0A1437D9383E6AD9AFEF6C5D8066ABA3ACA8C75D9F39120C444546492D4641355F424E421A30333744393338334536414439414645463643354438303636414241334143413843373544394633392D3630323436393012730A26EB5AE9872103BDB3430C322CC9C010DF575DC6593315EEB5424E0C62DCB6BF5DE72B5F2A963612405F08AA1E53E87521A06ED677111B37592025955600197DD5E72FB150E807AB6F1EE4457A830347CEA97E0EB461311DCDFBD3E9A9FEFFDD98E39AAFF93CCBDA7C18CAEB0C20FBDBEF02`

Can someone help me to understand the above error and/or know how to fix it?

**Comment by alexspark21** [comment]
Any news? I have at the same trouble with JS sdk

**Comment by blockmonk** [comment]
please check binance javascript sdk.
https://github.com/binance-chain/javascript-sdk

**Comment by blockmonk** [comment]
@alexspark21 if u needed I will provide Golang code in form of REST API where you can pass the hash from your js application and will receive txid.

**Comment by alexspark21** [comment]
@blockmonk JS SDK for now not supported Transfer type, and I can't decode encoded response from RPC to human response which doing perfectly HTTP API endpoint https://dex.binance.org/api/v1/transactions-in-block/61989125
