### ISSUE TITLE
Public key is null

### ISSUE THREAD

**Issue by dmitryrn** [binance-chain/node-binary#55]
I've created account with `createAccountWithKeystore` method, I've keep address and private key. When I get trying to get address with endpoint https://testnet-dex.binance.org/api/v1/account/tbnb1vme7c3kq4njqdmcr4dchd0xvy72wj0aqkjzhfs public_key is null and it causing in impossibility of transferring tokens in using SDK (it throws error inside because pubkey is null).

I cannot find any info how to update private key (from null to something) neither in SDK api nor in docs.

**Comment by HaoyangLiu** [comment]
> public_key is null 

This is because you have not sent transaction from this address. The pubkey can be derived from private key.

**Comment by dmitryrn** [comment]
Please take a look at this piece of code:
```js
const BnbApiClient = require('@binance-chain/javascript-sdk');
const ax = require('axios')

const l = x => console.log(JSON.stringify(x, null, 2))

const ad = 'tbnb1vme7c3kq4njqdmcr4dchd0xvy72wj0aqkjzhfs'
const pk = 'valid priv key'

const bnbAd = 'tbnb1r3ftne9unfdevyugcj6j2ymcp9k7t2vdngpwvy'
const bnbAdPk = 'valid pub key'

const apiUrl = 'https://testnet-dex.binance.org'

;(async() => {
  try {
    l('start')

    const bnbClient = new BnbApiClient(`${apiUrl}`);
    
    await bnbClient.setPrivateKey(bnbAdPk)
    await bnbClient.chooseNetwork("testnet");
    await bnbClient.initChain();

    const {data:sequence} = await ax(`${apiUrl}/api/v1/account/${ad}/sequence/`)
    l({sequence})

    const tx = await bnbClient.transfer(bnbAd, 'tbnb1jmrgd79fukdp8pmxjy902msjqfa389w4dzr6z3', 1, 'BNB')
    l({tx})

    l('end')
  } catch(e) {
    console.log(111, e.response ? e.response.data : e)
  }
})()
```

**Comment by dmitryrn** [comment]
I had tried to send coins both from `ad` to `bnbAd` and reverse with this code. But `transfer` throws error:
![image](https://user-images.githubusercontent.com/25539852/59350290-caae2a80-8d2c-11e9-9c9f-71012645b10f.png)

**Comment by dmitryrn** [comment]
So what can I do?

**Comment by dmitryrn** [comment]
@HaoyangLiu you saying that Ipubkey is null because I didn't send transaction from this address. But the issue is I can't send transaction from this address, error thrown, as you can see from the comments above.

**Comment by HaoyangLiu** [comment]
```
    await bnbClient.initChain();
    ...
    await bnbClient.setPrivateKey(bnbAdPk)
```
Maybe you can try to reverse the order to `initChain` and `setPrivateKey`.  By the way, it would be better if you can post javascript-sdk issues to [javascript-sdk issue](https://github.com/binance-chain/javascript-sdk/issues) in the future.
