### ISSUE TITLE
API server not starting panic: stat /root/.bnbcli/keys/keys.db: no such file or directory

### ISSUE THREAD

**Issue by 5hanth** [binance-chain/node-binary#56]
starting API server with following
`./tbnbcli api-server --chain-id "Binance-Chain-Nile" --node tcp://data-seed-pre-0-s1.binance.org:80 --laddr tcp://127.0.0.1:8080 --trust-node`

keys.db file is missing. is this something that has to be created before starting api server?

**Comment by huangsuyu** [comment]
> starting API server with following
> `./tbnbcli api-server --chain-id "Binance-Chain-Nile" --node tcp://data-seed-pre-0-s1.binance.org:80 --laddr tcp://127.0.0.1:8080 --trust-node`
> 
> keys.db file is missing. is this something that has to be created before starting api server?

Hello, 

you have to create a key to initialize your bnbcli home folder.

please do 

```
./tbbnbcli keys add XXX 
```
