### ISSUE TITLE
How to get tx fee

### ISSUE THREAD

**Issue by ruanqunfeng** [binance-chain/node-binary#60]
/api/v1/tx/{hash}  , by this command to get tx data , but I can't get tx fee.

{"code":0,"hash":"83B8393A0AB5C8468F0262B80104C770E0DA34CDE9CE370521444A37A39D4697","height":"21098465","log":"Msg 0: ","ok":true,"tx":{"type":"auth/StdTx","value":{"data":null,"memo":"","msg":[{"type":"cosmos-sdk/Send","value":{"inputs":[{"address":"tbnb138u9djee6fwphhd2a3628q2h0j5w97yx48zqex","coins":[{"amount":"20000000000","denom":"BNB"}]}],"outputs":[{"address":"tbnb1acqnwu3tvlfps95up52ptfve428mxd55z0gugs","coins":[{"amount":"20000000000","denom":"BNB"}]}]}}],"signatures":[{"account_number":"14","pub_key":{"type":"tendermint/PubKeySecp256k1","value":"A4q95eEn4cR1bbxVRqYc8pbLvKYyaMxjzaTSmkTJQUr6"},"sequence":"45718","signature":"ZvAlsOW67sQ7l6zcQz5xpK9T5TRK/Uy4D2fpheSQZNMayqC3OAKN3Rtj9Ec78TUJOYK75O6kYlqotgVHi0QDvg=="}],"source":"0"}}}

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/59508365-44d2e080-8ee0-11e9-9d07-4b9f0914d560.png)

The explorer has fee value

**Comment by ruanqunfeng** [comment]
So  how to get the tx fee by rpc command?

**Comment by huangsuyu** [comment]
> So how to get the tx fee by rpc command?

https://docs.binance.org/api-reference/dex-api/paths.html#apiv1fees

**Comment by ruanqunfeng** [comment]
> > So how to get the tx fee by rpc command?
> 
> https://docs.binance.org/api-reference/dex-api/paths.html#apiv1fees

Does the fee not change?  Or what is the regular of change?

**Comment by HaoyangLiu** [comment]
> Does the fee not change? Or what is the regular of change?

Transaction fee can only be changed by on-chain governance. This is a fee change proposal: https://explorer.binance.org/tx/F05315406E50A30C92187C3F7F11CA67EA219EDF0D1CF68AC60F810070A76B1A

**Comment by bantalon** [comment]
@HaoyangLiu
1. If I see such a Proposal request transaction, does it mean it is already approved?
1. How do I know the exact timestamp / block number the new fees are effective on?

**Comment by huangsuyu** [comment]
@bantalon the fee change proposal will take effect in the UTC midnight after the proposal is passed.

**Comment by bantalon** [comment]
@huangsuyu - You wrote _after the proposal is passed_. Can I assume that once the Proposal request transaction appear on the chain it means it is passed?

**Comment by huangsuyu** [comment]
Hello, @bantalon 

Validators of Binance Chain will vote on the proposal and a fee change proposal needs >50% yes votes to get it passed.
