### ISSUE TITLE
auth failure: secrect conn failed: EOF

### ISSUE THREAD

**Issue by anime8** [binance-chain/node-binary#64]
version:0.5.10
platform:centos7.5
env:testnet
hi, i got an error information when i run binance(default configuration) in testnet, and i tried to use version 0.5.8, it's still wrong. look at following:

**
I[2019-06-17|11:38:19.328] No peers available                           module=statesync height=0
I[2019-06-17|11:38:29.328] No peers available                           module=statesync height=0
I[2019-06-17|11:38:39.329] No peers available                           module=statesync height=0
E[2019-06-17|11:38:40.411] Dialing failed                               module=pex addr=8c379d4d3b9995c712665dc9a9414dbde5b30483@54.249.16.115:27146 err="auth failure: secrect conn failed: EOF" attempts=7
E[2019-06-17|11:38:40.414] Dialing failed                               module=pex addr=9612b570bffebecca4776cb4512d08e252119005@52.193.170.161:27146 err="auth failure: secrect conn failed: EOF" attempts=7
E[2019-06-17|11:38:40.416] Dialing failed                               module=pex addr=7156d461742e2a1e569fd68426009c4194830c93@13.112.215.16:27146 err="auth failure: secrect conn failed: EOF" attempts=7
E[2019-06-17|11:38:40.570] Dialing failed                               module=pex addr=381934b9b3f862d1e81e699d8e1d38929f330cef@54.158.222.212:27146 err="auth failure: secrect conn failed: EOF" attempts=7
E[2019-06-17|11:38:40.571] Dialing failed                               module=pex addr=fe5eb5a945598476abe4826a8d31b9f8da7b1a54@35.169.158.175:27146 err="auth failure: secrect conn failed: EOF" attempts=7
I[2019-06-17|11:38:40.572] added a peer                                 module=statesync peer=aea74b16d28d06cbfbb1179c177e8cd71315cce4
E[2019-06-17|11:38:40.666] Dialing failed                               module=pex addr=812497e2f2cbba7f5c49cc697ae8eb6b9bb9ef47@94.130.34.52:443 err="auth failure: secrect conn failed: unmarshal to [32]uint8 failed after 1 bytes (insufficient bytes decoding []byte of length 84): 5454502F312E31203430302042616420526571756573740D0A5365727665723A206E67696E780D0A446174653A204D6F6E2C203137204A756E20323031392030333A33383A343020" attempts=7
E[2019-06-17|11:38:40.877] Connection failed @ recvRoutine (reading byte) module=p2p peer=aea74b16d28d06cbfbb1179c177e8cd71315cce4@52.196.133.127:27146 conn=MConn{52.199.237.19:27146} err=EOF
E[2019-06-17|11:38:40.877] Stopping peer for error                      module=p2p peer="Peer{MConn{52.199.237.19:27146} aea74b16d28d06cbfbb1179c177e8cd71315cce4 out}" err=EOF
E[2019-06-17|11:38:40.878] MConnection flush failed                     module=p2p peer=aea74b16d28d06cbfbb1179c177e8cd71315cce4@52.196.133.127:27146 err="write tcp 192.168.23.152:57406->52.199.237.19:27146: use of closed network connection"
I[2019-06-17|11:38:40.878] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{52.199.237.19:27146} aea74b16d28d06cbfbb1179c177e8cd71315cce4 out}"
I[2019-06-17|11:38:40.878] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{52.199.237.19:27146} aea74b16d28d06cbfbb1179c177e8cd71315cce4 out}"
I[2019-06-17|11:38:42.574] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{52.199.237.19:27146} aea74b16d28d06cbfbb1179c177e8cd71315cce4 out}"
I[2019-06-17|11:38:49.328] No peers available                           module=statesync height=0
I[2019-06-17|11:38:59.328] No peers available                           module=statesync height=0
I[2019-06-17|11:39:09.328] No peers available                           module=statesync height=0
E[2019-06-17|11:39:10.602] Dialing failed                               module=pex addr=2726550182cbc5f4618c27e49c730752a96901e8@52.21.191.96:27146 err="auth failure: secrect conn failed: EOF" attempts=0
E[2019-06-17|11:39:11.165] Dialing failed                               module=pex addr=083c226a109b2e436f6ad2904f0bb29c0802893e@13.229.184.64:26656 err="dial tcp 13.229.184.64:26656: i/o timeout" attempts=7
E[2019-06-17|11:39:11.165] Dialing failed                               module=pex addr=2c1fa9c1698961da38d8cd50da9fe8b4bc433c50@34.202.245.91:26856 err="dial tcp 34.202.245.91:26856: i/o timeout" attempts=7
E[2019-06-17|11:39:11.165] Dialing failed                               module=pex addr=e06945c097a20311cae9df569fc4d252b2b63f85@34.202.245.91:26856 err="dial tcp 34.202.245.91:26856: i/o timeout" attempts=7
I[2019-06-17|11:39:19.328] No peers available                           module=statesync height=0
I[2019-06-17|11:39:29.331] No peers available                           module=statesync height=0
I[2019-06-17|11:39:39.329] No peers available                           module=statesync height=0
**

**Comment by huangsuyu** [comment]
Hello,

Can you try to delete your `node_key.json` and restart again?

Thanks

**Comment by anime8** [comment]
@huangsuyu 
I tried, but it was still wrong with following information:

_
[root@template-7 ba]# ./bin/bnbchaind start --home `pwd` --pruning breathe 
panic: Tendermint state.AppHash does not match AppHash after replay. Got , expected 393887B67F69B19CAB5C48FB87B4966018ABA893FB3FFD241C0A94D2C8668DD2

goroutine 1 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.checkAppHash(0xa, 0x0, 0xc000bd8c56, 0x6, 0xc000b247c0, 0x12, 0x14e7bf9, 0x8592eb, 0xc000b247e0, 0x20, ...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:464 +0x213
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000b37980, 0xa, 0x0, 0xc000bd8c56, 0x6, 0xc000b247c0, 0x12, 0x14e7bf9, 0x8592eb, 0xc000b247e0, ...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:335 +0xf95
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000b37980, 0x13fec00, 0xc0008f9340, 0x2, 0x13eaa40)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:264 +0x6fa
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node.NewNode(0xc0000c8b40, 0x13eabc0, 0xc000893e00, 0xc00087c680, 0x13cc180, 0xc000b60460, 0xc00087cc90, 0x1273ec0, 0xc00087cca0, 0x13eaa40, ...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node/node.go:291 +0xe3a
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00088bca0, 0x1274748, 0x1d, 0x0, 0x0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:132 +0x524
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000929d40, 0xc0008fb1c0, 0x0, 0x4, 0x0, 0x0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:44 +0xb5
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc000929d40, 0xc0008fb180, 0x4, 0x4, 0xc000929d40, 0xc0008fb180)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0009286c0, 0x2, 0xc00088bec0, 0x111a7cf)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0009286c0, 0x1274b50, 0x2, 0xc000b49130)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/huangsuyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:53 +0x396
[root@template-7 ba]# ./bin/bnbchaind start --home /opt/software/ba/ --pruning breathe 
panic: Tendermint state.AppHash does not match AppHash after replay. Got , expected 393887B67F69B19CAB5C48FB87B4966018ABA893FB3FFD241C0A94D2C8668DD2

goroutine 1 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.checkAppHash(0xa, 0x0, 0xc000b24730, 0x6, 0xc0009b04c0, 0x12, 0x14e7bf9, 0x8592eb, 0xc0009b0500, 0x20, ...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:464 +0x213
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000a55c80, 0xa, 0x0, 0xc000b24730, 0x6, 0xc0009b04c0, 0x12, 0x14e7bf9, 0x8592eb, 0xc0009b0500, ...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:335 +0xf95
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000a55c80, 0x13fec00, 0xc000b57420, 0x2, 0x13eaa40)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/consensus/replay.go:264 +0x6fa
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node.NewNode(0xc0000c8b40, 0x13eabc0, 0xc000081ae0, 0xc000a8c3e0, 0x13cc180, 0xc0000a1540, 0xc000a8c660, 0x1273ec0, 0xc000a8c670, 0x13eaa40, ...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/node/node.go:291 +0xe3a
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00023fb40, 0x1274748, 0x1d, 0x0, 0x0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:132 +0x524
github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc00001bd40, 0xc000334980, 0x0, 0x4, 0x0, 0x0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/cosmos/cosmos-sdk/server/start.go:44 +0xb5
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).execute(0xc00001bd40, 0xc000334940, 0x4, 0x4, 0xc00001bd40, 0xc000334940)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00001a6c0, 0x2, 0xc00023fd60, 0x111a7cf)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/binance-chain/node/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/spf13/cobra/command.go:736
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00001a6c0, 0x1274b50, 0x2, 0xc000b24fd0)
	/Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/huangsuyu/go/src/github.com/binance-chain/node/cmd/bnbchaind/main.go:53 +0x396

_

**Comment by huangsuyu** [comment]
Hello, @anime8 

Have you followed these instruction: https://docs.binance.org/fullnodeissue.html#apphash-confliction for a complete reset?

**Comment by anime8** [comment]
Hello, @huangsuyu 
  Thanks, i'm trying.

**Comment by anime8** [comment]
Hello, @huangsuyu 
  It works, thanks very much!

**Comment by huangsuyu** [comment]
> Hello, @huangsuyu
> It works, thanks very much!

Good to know!
