### ISSUE TITLE
TxSearch RPC call as specified in the docs not working

### ISSUE THREAD

**Issue by sidshekhar** [binance-chain/node-binary#65]
I have a local light node connected to Binance-Chain-Tigris and I am able to execute other RPC calls with ease. 

However when I follow the documentation at [https://docs.binance.org/api-reference/node-rpc.html#6115-query-txsearch](https://docs.binance.org/api-reference/node-rpc.html#6115-query-txsearch) and try 
`curl "localhost:27147/tx_search?query=\"tx.height=10000\"&prove=true"` 

I get 

`404 page not found`. 

Would love some help with this. The problem we are trying to solve is to get all the transaction hashes that are in any given block.

**Comment by huangsuyu** [comment]
Please note that on Binance Chain testnet, you can only use this data seed node for tx search: https://data-seed-pre-0-s3.binance.org

And to enable your own node, set `index_tags = "tx.height"` in your `config.toml`
