### ISSUE TITLE
Testnet !  ERROR: No account with address was found in the state. 

### ISSUE THREAD

**Issue by prateektiwari7** [binance-chain/node-binary#67]
Hello Guys

I am stuck with error in testnet while issuing the token in Binance chain. 

Here is the output of `./tbnbcli keys list`

`NAME:	TYPE:	ADDRESS:						PUBKEY:
prateek	local	tbnb183an6768uevylrzaxj9476hk6yskd9sgnuuq9y	bnbp1addwnpepq22uzsc4qrx32c25mhckd8mdevmny8fsr6juxthf5vmmawstvkua6fjf3x7
test_key	local	tbnb1uelwue8gq4dqllwcc89xxvemxjyajgdrrwxhzj	bnbp1addwnpepqdmg8jjp4k00dt6xjw9gtf225knc2cl4e0atgrdpmk6egycp9xxvvlay7hg`

And I am also ruining one local test client as 
`./tbnbcli api-server --chain-id "Binance-Chain-Nile" --node tcp://data-seed-pre-0-s1.binance.org:80 --laddr tcp://127.0.0.1:8080 --trust-node`
**And this is working very fine and connected to testnetwork**

But when I am trying to issue the token with command as 
`./tbnbcli token issue --token-name "new bnb" --total-supply 100000000000000000 --symbol NNB --from prateek  --chain-id=Binance-Chain-Nile --node=data-seed-pre-2-s1.binance.org:80 --trust-node`

I am getting error like 
`ERROR: No account with address tbnb183an6768uevylrzaxj9476hk6yskd9sgnuuq9y was found in the state.
Are you sure there has been a transaction involving it?`

I also tried to replace --from with address but still it is not working. 

Please help me to find solution.

Thanks

**Comment by prateektiwari7** [comment]
Do I need to add 1 BNB for testing?

I got this from Binance doc !

`
Note: To obtain Binance Chain testnet funds, you must have a Binance account that has a minimum of 1 BNB in it. The 1 BNB will remain in your account and can be withdrawn or traded after requesting testnet BNB for the Binance Chain. The 1 BNB requirement is merely an anti-spam measure`. 


[Here](https://www.binance.vision/tutorials/binance-dex-funding-your-testnet-account)

**Comment by huangsuyu** [comment]
Hello, @prateektiwari7 It seems your account balance is empty, please make sure you have non-zero balance.

**Comment by prateektiwari7** [comment]
Hello @huangsuyu 

How should I add BNB on testnet?

**Comment by prateektiwari7** [comment]
@huangsuyu  Can you please help me to get at least 1 BNB to test my work on testnet?

**Comment by huangsuyu** [comment]
> @huangsuyu Can you please help me to get at least 1 BNB to test my work on testnet?

i think you can post your address here, i can send you some testnet token

**Comment by prateektiwari7** [comment]
Thank you very much @huangsuyu sir. 

Can you please check whether my steps are correct or not. 

I am connected with the testnet network of binance by the following steps !

**Under the directory of node-binary**

1. `./tbnbcli api-server --chain-id "Binance-Chain-Nile" --node tcp://data-seed-pre-0-s1.binance.org:80 --laddr tcp://127.0.0.1:8080 --trust-node`

2. **It gives me the output of rest server started as** 

`I[2019-06-27|10:51:51.002] REST server started                          module=apiserv 
I[2019-06-27|10:51:51.002] Starting RPC HTTP server on 127.0.0.1:8080   module=apiserv `

3. And ruining this URL in the browser gives me enough data. Looks like 

`http://localhost:8080/api/v1/markets` 

4. If I use this command while my 1st step is already ruining. It shows me this error.

`ERROR: resource temporarily unavailable` 

5. But If I close my 1st step process it shows me full functionality 

`./tbnbcli keys add TESTING
Enter a passphrase for your key:
Repeat the passphrase:
NAME:	TYPE:	ADDRESS:						PUBKEY:
TESTING	local	tbnb1ex8zs9ma65m80put7lxl6tfry7aslatq6axp9r	bnbp1addwnpepqgfk8dvyrn9zhjt6n452peckmdpr37hzl6cg8t98rxmkg7aajjrtjgajng4`

6. These keys which are generated are correct right ? Can I use them to use testnet ? 

If yes than please share me the some test BNB to do some testing 


Thank you :)

**Comment by huangsuyu** [comment]
that function is not available in api-server. Please read this: https://docs.binance.org/api-reference/api-server.html

**Comment by prateektiwari7** [comment]
So how should I connect my testnet cli with the testnet to create keys and use it to issue tokens on testnet?

**Comment by prateektiwari7** [comment]
Is there anything wrong in the creation of my testnet keys?  Can you send me some test BNB if it is correct?

**Comment by prateektiwari7** [comment]
@huangsuyu Can you please check above comment?
