### ISSUE TITLE
0.5.8.1 tbnbcli has a wrong default value for voting_period

### ISSUE THREAD

**Issue by kylidboy** [binance-chain/node-binary#69]
when I tried to submit my list proposal, I didn't specify --voting_period. The proposal is ok, but the voting period from query-proposal is 604800000000000, which is 70 days.

{                                        
  "type": "gov/TextProposal",                                   
  "value": {                                                      
    "proposal_id": "740",                                                                                                                    
    "title": "“list",                                                                                                                        
    "description": "{\"base_asset_symbol\":\"ATP.B-CCF\",\"quote_asset_symbol\":\"BNB\",\"init_price\":100000000,\"description\":\"“list\",\"expire_time\":\"2019-07-26T17:56:09+08:00\"}",
    "proposal_type": "ListTradingPair",                                                                                                      
    "voting_period": "604800000000000",                
    "proposal_status": "VotingPeriod",                     
    "tally_result": {                                                                                                                        
      "yes": "0",                                         
      "abstain": "0",                                                                                                                        
      "no": "0",                                                                                                                             
      "no_with_veto": "0",                                                                                                                   
      "total": "0"                                                                                                                           
    },                                                                                                                                       
    "submit_time": "2019-06-26T09:57:09.899391783Z",            
    "total_deposit": [                                           
      {                                                                                                                                      
        "denom": "BNB",                                                                                                                      
        "amount": "200000000000"                                                                                                             
      }                                                                                                                                      
    ],                                                                
    "voting_start_time": "2019-06-26T09:57:09.899391783Z"         
  }                                                                                                                                          
}

**Comment by huangsuyu** [comment]
Hello, @kylidboy 

The voting period is in nano seconds as in `unix timestamp`. It's still a week.
