### ISSUE TITLE
Unsupported 16-bit application error

### ISSUE THREAD

**Issue by Rombusz** [binance-chain/node-binary#70]
The 0.6.0 windows release doesnt run on windows 10 64 bit. When trying to run tbnbcli.exe from command line the following error dialog pops up.

OS version is: 10.0.17763 Build 17763

![image](https://user-images.githubusercontent.com/7734664/60267275-2a3e3580-98ea-11e9-9ee5-9224b0cec7a6.png)

**Comment by fanbsb** [comment]
Same for me, unbelievable the windows version is 16-bit

**Comment by blockmonk** [comment]
i am getting the same error with new version 0.6.0 also known as a stable version @fanbsb @Rombusz 
got any solution?

**Comment by huangsuyu** [comment]
> i am getting the same error with new version 0.6.0 also known as a stable version @fanbsb @Rombusz
> got any solution?

Please test  the latest binary of `bnbcli`, it's been updated

**Comment by Rombusz** [comment]
> > i am getting the same error with new version 0.6.0 also known as a stable version @fanbsb @Rombusz
> > got any solution?
> 
> Please test the latest binary of `bnbcli`, it's been updated

Version 0.6.1 works for me. Thank you.

**Comment by huangsuyu** [comment]
Thanks,  @Rombusz 

I will close this now.
