### ISSUE TITLE
How to expose or print local keys' privateKey and mnemonics?

### ISSUE THREAD

**Issue by testrain** [binance-chain/node-binary#71]
Hello,

I'm using `bnbcli/tbnbcli` locally on my Ubuntu machine. I've created an account with several funds in it. I'm wondering is there any commands / ways to expose / print the private key or mnemonic of the account?

I think there should be, as the account secrets are stored in local db and I could use cli to sign tx or send funds.

But just that I do not find how to do it anywhere from the documentation.

Thanks!

**Comment by HaoyangLiu** [comment]
```
$ bnbcli keys add test1
Enter a passphrase for your key:
Repeat the passphrase:
NAME:	TYPE:	ADDRESS:						PUBKEY:
test1	local	bnb1dkee0gnt9wmhc4v08gkrm538rkuwmq0mrn66s6	bnbp1addwnpepqgpy99fr9nkx9ffmqx52v43ss3yhxnktpl50fwnkvcfxp4kpksc7gluk9zx
**Important** write this seed phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

before shine happy army problem chunk cement spike expire stamp human enroll amount lava crawl imitate glide treat rebel tuna tide galaxy glance pencil
```
When you create a key with `bnbcli/tbnbcli`, it will print out the mnemonic: 24 words. You'd better write them on your paper. But if you don't do that, you can't get the mnemonic later, because currently we don't support the exporting functionality in `bnbcli/tbnbcli`.

**Comment by huangsuyu** [comment]
Great answer from @HaoyangLiu, and this example can be found in the doc: https://docs.binance.org/keys.html#create-a-new-key

**Comment by testrain** [comment]
Hi guys,

Thank you and yeah I understand how to add a new local key or recover from given mnemonics. 

> But if you don't do that, you can't get the mnemonic later, because currently we don't support the exporting functionality in bnbcli/tbnbcli.
Then can we add this feature to the next release of bnbcli tools? The mnemonics is stored locally in leveldb, we need a way for owners to expose / print clear-text mnemonics just in case the owner didn't keep a copy on paper - like me.

**Comment by testrain** [comment]
It seems I could not add `feature-request` tab or assign to anyone.

If you guys agree with my point, can you please make a feature request on behave of me? Thank you all!
@HaoyangLiu  @huangsuyu

**Comment by 0xfff** [comment]
i am trying to run a bridge tx using `bnbcli` 0.8.2
```
$ bnbcli bridge transfer-out --to 0x... --expire-time 1627253349 --chain-id Binance-Chain-Tigris --from owner --amount 0.0001:BNB --node http://dataseed4.binance.org:80
```
i get:
`could not find key owner`

what does that mean?


```
$ bnbcli keys list
NAME:	TYPE:	ADDRESS:						PUBKEY:
test_key	local	bnb...	bnb...
```
