### ISSUE TITLE
Trying to connect Ledger Nano to the cli

### ISSUE THREAD

**Issue by omrierez** [binance-chain/node-binary#77]
I am getting on windows cli version 0.5.8.1
 
"ERROR: no ledger discovery function defined " when trying to add the key from the hardware ledger device

**Comment by HaoyangLiu** [comment]
Can you try this on ubuntu or MacOS?

**Comment by seb0zz** [comment]
Same issue on MacOS with version `0.6.3`. It does not happen with `0.6.2`.
