### ISSUE TITLE
can't execute bnbchaind binary on v0.6.0 (linux)

### ISSUE THREAD

**Issue by skinderis** [binance-chain/node-binary#78]
trying to execute `./bnbchaind --help` (in node-binary/fullnode/prod/0.6.0/linux), it returns an error:

```
./bnbchaind: 1: ./bnbchaind: version: not found
./bnbchaind: 2: ./bnbchaind: oid: not found
size: '37036047': No such file
```

**Comment by skinderis** [comment]
v0.5.9 works fine.

**Comment by huangsuyu** [comment]
Hello, @skinderis 

Please use `git lfs clone` to get the whole binary.

thanks.

**Comment by skinderis** [comment]
@huangsuyu thanks, yesterday did it with git lfs clone, today retried it, now it works.
