### ISSUE TITLE
Is there a full node backup?

### ISSUE THREAD

**Issue by singpenguin** [binance-chain/node-binary#79]
My node 0.6.0 upgrade failed, but the data directory has been deleted, the resynchronization data is very slow, is there a complete node data backup that can be downloaded?
Thanks.

**Comment by huangsuyu** [comment]
Hello, @singpenguin 

Can you provide more details about your error?

If you use state-sync, you can get synced fast. just download the config files to a new home folder and run `bnbchaind start`.

**Comment by singpenguin** [comment]
是这样，0.6.0正式版本没有出来时，还没升级，过了两天正式版本出来了，没注意到，导致我的0.5.9版本停止同步了，我下载了0.6.0也无法同步，提示不能match的那个问题，但是这时候我把data目录删除了，想重新同步，结果0.6.0版本同步非常慢，一天时间才同步200万高度，完全同步完要2周，我们的服务无法接受这样暂停时间，想问下，有没有完整的node数据备份，我下载更新一下，这样也不用从头开始同步了。

@huangsuyu

**Comment by huangsuyu** [comment]
你是不是没有在config.toml文件中使用state-sync?

请做如下修改，在config.toml文件中，
```
state_sync_reactor = true
state_sync_height = 0
```

然后删删除data目录，再重新同步就可以了

**Comment by huangsuyu** [comment]
@singpenguin 

能不能提供0.5.9版本停止同步完整的错误信息？

**Comment by singpenguin** [comment]
bnc.log 昨晚刚删除，错误信息大概就是 header not mathc, got XXXXXXXXX，就自动退出了。

加了您说的两个配置后，确实同步快了，我看下数据正常不正常。谢谢啦

**Comment by singpenguin** [comment]
同步高度到 19298100 就停止了。
@huangsuyu

**Comment by huangsuyu** [comment]
> 同步高度到 19298100 就停止了。
> @huangsuyu

有报错信息吗？

**Comment by singpenguin** [comment]
真抱歉，日志已经删完了，[Facepalm][Facepalm]，不然就贴出来了。
当时的情况就是，在19298100高度以下的块不停的循环解析，应该有1万个块吧，解析完了又倒回去了，后来更新bnbchaind后，重启就启动不了。
[Facepalm]

**Comment by huangsuyu** [comment]
请务必删除data目录和config/priv_validator_key.json
然后重启bnbchaind，这样就可以重新以state-sync方式同步

**Comment by singpenguin** [comment]
好的，已解决，非常感谢。

**Comment by singpenguin** [comment]
@huangsuyu 
又出现了循环同步的问题了。

**Comment by singpenguin** [comment]
I[2019-07-15|11:14:49.731] replayed all tx. Starting match              module=dex height=20299997
I[2019-07-15|11:14:49.731] Relaying block for order book                module=dex height=20299998
I[2019-07-15|11:14:49.731] replayed all tx. Starting match              module=dex height=20299998
I[2019-07-15|11:14:49.731] No new orders for any pair, give up matching module=dexkeeper 
I[2019-07-15|11:14:49.731] No order comes in for the block              module=dexkeeper 
I[2019-07-15|11:14:49.731] Relaying block for order book                module=dex height=20299999
I[2019-07-15|11:14:49.731] Canceled Order                               module=dex order="CancelOrderMsg{Sender:68217A1DE62DEC6878C6752BCF092F9B45968085, RefId: 68217A1DE62DEC6878C6752BCF092F9B45968085-36376}"
I[2019-07-15|11:14:49.731] replayed all tx. Starting match              module=dex height=20299999
I[2019-07-15|11:14:49.731] No new orders for any pair, give up matching module=dexkeeper 
I[2019-07-15|11:14:49.731] No order comes in for the block              module=dexkeeper 
I[2019-07-15|11:14:49.731] Relaying block for order book                module=dex height=20300000
I[2019-07-15|11:14:49.731] Added Order                                  module=dex order="NewOrderMsg{Sender: 8FE142DB8CEF4C0F75F418430D0A83F2A60C7FB1, Id: 8FE142DB8CEF4C0F75F418430D0A83F2A60C7FB1-148635, Symbol: UND-EBC_BNB}"
I[2019-07-15|11:14:49.731] Added Order                                  module=dex order="NewOrderMsg{Sender: 8FE142DB8CEF4C0F75F418430D0A83F2A60C7FB1, Id: 8FE142DB8CEF4C0F75F418430D0A83F2A60C7FB1-148636, Symbol: UND-EBC_BNB}"
I[2019-07-15|11:14:49.731] replayed all tx. Starting match              module=dex height=20300000
I[2019-07-15|11:14:49.840] Located day to load breathe block height     module=dexkeeper epochDay="\ufffdF\u0000\u0000\u0000\u0000\u0000\u0000"
I[2019-07-15|11:14:49.840] Loaded breathe block height                  module=dexkeeper height=20219382
I[2019-07-15|11:14:49.840] get last breathe block height                module=main height=20219382
I[2019-07-15|11:14:49.841] reload latest snapshot                       module=statesync height=20219382
I[2019-07-15|11:14:49.909] ABCI Handshake App Info                      module=consensus height=20300000 hash=27EAAF94E6D1D91453E1EE01980EC97CA198ADFD585D65631858D5417896B3FA software-version= protocol-version=0
I[2019-07-15|11:14:49.917] ABCI Replay Blocks                           module=consensus appHeight=20300000 storeHeight=20300001 stateHeight=20300000
I[2019-07-15|11:14:49.917] Replay last block using real app             module=consensus 
I[2019-07-15|11:14:50.973] Starting ABCI with Tendermint                module=main 
I[2019-07-15|11:14:51.210] Located day to load breathe block height     module=dexkeeper epochDay="\ufffdF\u0000\u0000\u0000\u0000\u0000\u0000"
I[2019-07-15|11:14:51.210] Loaded breathe block height                  module=dexkeeper height=20219382
I[2019-07-15|11:14:51.210] Loading order book snapshot from last breathe block module=main blockHeight=20219382
I[2019-07-15|11:14:51.242] Successfully Loaded order snapshot           module=main pair="{BaseAssetSymbol:ANKR-E97 QuoteAssetSymbol:BNB ListPrice:0.00024023 TickSize:0.00000001 LotSize:10.00000000}"
I[2019-07-15|11:14:51.242] Successfully Loaded order snapshot           module=main pair="{BaseAssetSymbol:ANKR-E97 QuoteAssetSymbol:BTCB-1DE ListPrice:0.00000069 TickSize:0.00000001 LotSize:10000.00000000}"

**Comment by singpenguin** [comment]
![Uploading 1563189574215.jpg…]()

**Comment by singpenguin** [comment]
![1563189574215](https://user-images.githubusercontent.com/1811606/61214160-bac5a400-a739-11e9-82f2-0973c4a610a1.jpg)

**Comment by singpenguin** [comment]
@huangsuyu 应该是seeds节点的数据坏了，停止在高度20300000和20219382, 麻烦尽快修复一下，同步了好几遍，都是到这就重新开始了。

**Comment by Alteryy** [comment]
请问我启动的时候怎么报这个错？
$/node-binary-0.6.0/fullnode/prod/0.6.0/linux# ./bnbchaind start --home /root/.bnbchaind
./bnbchaind: line 1: version: command not found
./bnbchaind: line 2: oid: command not found
size: '37036047': No such file

**Comment by guagualvcha** [comment]
> @huangsuyu 应该是seeds节点的数据坏了，停止在高度20300000和20219382, 麻烦尽快修复一下，同步了好几遍，都是到这就重新开始了。

你的进程配置了自动重启吧，所以开起来在这执行了好几遍，因为进程每次启动的时候都会replay状态恢复orderbook。 你需要按照sophie说的，删除数据，用state_sync下载最新的数据，这样追上我们的最新高度只需要半小时。

**Comment by huangsuyu** [comment]
> @huangsuyu 应该是seeds节点的数据坏了，停止在高度20300000和20219382, 麻烦尽快修复一下，同步了好几遍，都是到这就重新开始了。

昨天币安链完成了升级，如果你没有更换配置文件，就无法与网络同步。seed节点都在正常运行。
请保证config.toml， app.toml文件已经替换为最新的。

**Comment by singpenguin** [comment]
@guagualvcha 昨天半夜又试了一次，最后同步成功了。
