### ISSUE TITLE
Can`t start full node

### ISSUE THREAD

**Issue by prettyCoders** [binance-chain/node-binary#80]
![image](https://user-images.githubusercontent.com/36216120/61262255-43cef080-a7b7-11e9-8a66-143b304093de.png)

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/61263078-3b2be980-a7ba-11e9-9dd8-f94921a8b409.png)
Same target

**Comment by huangsuyu** [comment]
Hello, @prettyCoders 

Please refer to the latest doc: https://docs.binance.org/fullnode.html#state-sync


And please download binary with `git lfs`: https://docs.binance.org/fullnode.html#download-binary-with-git-lfs
