### ISSUE TITLE
how to resolve the problem ? curl "localhost:27147/tx_search?query=\"tx.height=21182080\"&prove=true"

### ISSUE THREAD

**Issue by wade-liwei** [binance-chain/node-binary#84]
curl "localhost:27147/tx_search?query=\"tx.height=21182080\"&prove=true"

I try the command, but I can not get tx list.
If I use the command curl "localhost:27147/tx_search?query=\"tx.height=21182080\"&prove=true"
I can see the tx data.

Please help me!

**Comment by huangsuyu** [comment]
You need to enable indexer in config.tml. You can modify the index_tags to tx.height, which is the only tag we support now. In this way, you can index transactions by height by adding "tx.height" tag here.
