### ISSUE TITLE
module=main err="version does not exist"

### ISSUE THREAD

**Issue by jakilwq** [binance-chain/node-binary#90]
the node always broken down  when it sync height 20300000:

I[2019-07-31|14:42:48.245] Added Order                                  module=dex order="NewOrderMsg{Sender: 8FE142DB8CEF4C0F75F418430D0A83F2A60C7FB1, Id: 8FE142DB8CEF4C0F75F418430D0A83F2A60C7FB1-148636, Symbol: UND-EBC_BNB}"
I[2019-07-31|14:42:48.245] replayed all tx. Starting match              module=dex height=20300000
I[2019-07-31|14:42:48.593] Located day to load breathe block height     module=dexkeeper epochDay="\ufffdF\u0000\u0000\u0000\u0000\u0000\u0000"
I[2019-07-31|14:42:48.593] Loaded breathe block height                  module=dexkeeper height=20219382
I[2019-07-31|14:42:48.593] get last breathe block height                module=main height=20219382
I[2019-07-31|14:42:48.605] reload latest snapshot                       module=main height=20219382
E[2019-07-31|14:42:48.605] failed to load immutable tree                module=main err="version does not exist"
I[2019-07-31|14:42:48.887] ABCI Handshake App Info                      module=consensus height=20300000 hash=27EAAF94E6D1D91453E1EE01980EC97CA198ADFD585D65631858D5417896B3FA software-version= protocol-version=0
I[2019-07-31|14:42:48.889] ABCI Replay Blocks                           module=consensus appHeight=20300000 storeHeight=20300001 stateHeight=20300000
I[2019-07-31|14:42:48.889] Replay last block using real app             module=consensus

**Comment by huangsuyu** [comment]
which version do you use?

**Comment by jakilwq** [comment]
> which version do you use?

0.5.10

**Comment by jakilwq** [comment]
> > which version do you use?
> 
> 0.5.10

i try to use 0.6.0 ,but is not a executable file

**Comment by huangsuyu** [comment]
you must use git lfs clone to get the binaries

**Comment by jakilwq** [comment]
> you must use git lfs clone to get the binaries

now i git clone newest .but 0.6.0 and 0.6.1 already not executable file
please check it

**Comment by jakilwq** [comment]
> > you must use git lfs clone to get the binaries
> 
> now i git clone newest .but 0.6.0 and 0.6.1 already not executable file
> please check it

fullnode/prod/0.6.0/linux/bnbchaind: text/plain; charset=us-ascii
fullnode/prod/0.6.1/linux/bnbchaind: text/plain; charset=us-ascii

**Comment by huangsuyu** [comment]
if you dont know how to use `git lfs clone`, you can just go to the page and click on download button
