### ISSUE TITLE
Ciphertext decryption failed

### ISSUE THREAD

**Issue by avicse1** [binance-chain/node-binary#91]
For creating token, when I am executing the below command, I was getting Ciphertext decryption failed error. How can I solve this?
![Screenshot from 2019-08-02 19-45-20](https://user-images.githubusercontent.com/28019637/62376357-17a8c300-b55e-11e9-80c3-3f614a39549d.png)

avinash@grim-reaper:~/src/node-binary/tools$ ./tbnbcli token issue -s DIGTOK --token-name "DIGGITOKEN" --total-supply 1000000000000000000 --from diggiblip --mintable=false --chain-id Binance-Chain-Nile --node=http://data-seed-pre-2-s1.binance.org:80
Password to sign with 'diggiblip':
ERROR: Ciphertext decryption failed

**Comment by huangsuyu** [comment]
Hello, @avicse1 

The error means your password is incorrect. please check!

**Comment by avicse1** [comment]
@huangsuyu you mean the wallet password. I tried with the right password but the error is same

**Comment by huangsuyu** [comment]
@avicse1 

Yes, I think your password is not correct. can you use seed phrase to reset that please?

**Comment by avicse1** [comment]
@huangsuyu Thanks it worked. Actually, the password was 24 words key pass
