### ISSUE TITLE
node stopped at 25120000

### ISSUE THREAD

**Issue by bitcodernull** [binance-chain/node-binary#92]
node stopped at 25120000
the error is:

I[2019-08-05|13:11:00.327] replayed all tx. Starting match              module=dex height=25120000
I[2019-08-05|13:11:01.828] ABCI Handshake App Info                      module=consensus height=25120000 hash=9B3777FD460822F10E9BF06888DC02B6D2535D7D72965C9B0E9AF11AB2BC0901 software-version= protocol-version=0
I[2019-08-05|13:11:01.833] ABCI Replay Blocks                           module=consensus appHeight=25120000 storeHeight=25120000 stateHeight=25120000
I[2019-08-05|13:11:01.833] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=25120000 appHash=9B3777FD460822F10E9BF06888DC02B6D2535D7D72965C9B0E9AF11AB2BC0901
I[2019-08-05|13:11:01.833] This node is not a validator                 module=consensus addr=7AD900D4A7DE0CF90B58342E56D4CF6450E0CFD1 pubKey=PubKeyEd25519{69FB9D3443FB2BA289BBC2632DEFAA86FE5A68C1C068432B489F360659D447BC}
I[2019-08-05|13:11:01.856] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[2019-08-05|13:11:01.856] Starting BlockPool                           module=blockchain impl=BlockPool
I[2019-08-05|13:11:01.856] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[2019-08-05|13:11:01.856] ConsensusReactor                             module=consensus fastSync=true
E[2019-08-05|13:11:03.172] Dialing failed                               module=pex addr=29792743565c4470480dbf7ef43b9256465dfa74@99.81.122.88:27146 err="dial tcp 99.81.122.88:27146: i/o timeout" attempts=0
E[2019-08-05|13:11:03.645] Connection failed @ recvRoutine (reading byte) module=p2p peer=48dada912ff10f04dec0db7900a78750384d06fd@52.31.30.219:27146 conn=MConn{52.31.30.219:27146} err=EOF
E[2019-08-05|13:11:03.645] Stopping peer for error                      module=p2p peer="Peer{MConn{52.31.30.219:27146} 48dada912ff10f04dec0db7900a78750384d06fd out}" err=EOF
I[2019-08-05|13:11:03.655] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{52.31.30.219:27146} 48dada912ff10f04dec0db7900a78750384d06fd out}"
I[2019-08-05|13:11:03.655] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{52.31.30.219:27146} 48dada912ff10f04dec0db7900a78750384d06fd out}"
E[2019-08-05|13:11:03.709] Dialing failed                               module=pex addr=bb721fe089e83d42bcb8f629f8efe0e4af888fde@52.197.88.253:27146 err="auth failure: conn.ID (98579505572cc85488caa403bebb62e5b61d68e0) dialed ID (bb721fe089e83d42bcb8f629f8efe0e4af888fde) mismatch" attempts=0
E[2019-08-05|13:11:03.818] Dialing failed                               module=pex addr=28972d18d1bfdab699b5979ad82ec64534f22e32@3.82.70.135:27146 err="duplicate CONN<3.82.70.135:27146>" attempts=0
E[2019-08-05|13:11:03.819] Dialing failed                               module=pex addr=0f57cb3d73ea4b2be45d5e01f25871ed82f58a05@3.82.70.135:27146 err="duplicate CONN<3.82.70.135:27146>" attempts=0
E[2019-08-05|13:11:04.039] Dialing failed                               module=pex addr=a81f0874a86c5553d761190e20e9e12eea277ad8@3.82.70.135:27146 err="auth failure: conn.ID (af89cf5aa3aff6d8b3f60043b8706dc458293b7f) dialed ID (a81f0874a86c5553d761190e20e9e12eea277ad8) mismatch" attempts=0

**Comment by bitcodernull** [comment]
i use tools to reset the block data   ./state_recover 25118000 ../node/

restart the node, and i got the following errors:

panic: Failed to process committed block (25120001:3741D350B55D07017F39209DD36231372DEB5FB49082A699B0F268BEB02FA7DC): Wrong Block.Header.AppHash.  Expected 9B3777FD460822F10E9BF06888DC02B6D2535D7D72965C9B0E9AF11AB2BC0901, got 974B56A413D30A923B80C8AEA337B028086A8EFE149934C3ACD176C81FE333D2

goroutine 68591 [running]:
github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0008d21a0)
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:372 +0x1874
created by github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /Users/huangsuyu/go/src/github.com/binance-chain/node/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:117 +0x84

**Comment by yutianwu** [comment]
have you update the binary?

**Comment by bitcodernull** [comment]
it is ok now

my app.toml missed the configuration :
BEP12Height = 25120000

i add it and restart the node, the node is ok now

thanks
