### ISSUE TITLE
Start bnb is error

### ISSUE THREAD

**Issue by ruanqunfeng** [binance-chain/node-binary#93]
![image](https://user-images.githubusercontent.com/15098545/62443696-24136280-b78e-11e9-88ef-7bd310d20774.png)

**Comment by huangsuyu** [comment]
Hello, @ruanqunfeng 

Please use `git lfs clone` to get the whole binary

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/62445216-4c9d5b80-b792-11e9-97b2-83cf63938703.png)
Hello, there is a new error
