### ISSUE TITLE
How to decode the response of ABCIQuery(Node RPC) ?

### ISSUE THREAD

**Issue by Brochao** [binance-chain/node-binary#95]
Trying to get account balance by using Node RPC API  as mentioned [here](https://docs.binance.org/api-reference/node-rpc.html#619-abciquery).

how can I decode the amino-encoded response to JSON result as shown in the document ?

**Comment by huangsuyu** [comment]
Hello, @Brochao 

Can you take a look of how it's implemented in go-sdk: https://github.com/binance-chain/go-sdk/blob/3f52c489082684ec2384acdcb73ffa8ad940ccf7/client/rpc/dex_client.go#L107

**Comment by Brochao** [comment]
thanks! @huangsuyu 
problem solved!
