### ISSUE TITLE
How to make the Node decode transactions

### ISSUE THREAD

**Issue by YordanPavlov** [binance-chain/node-binary#96]
If I am willing to run my own Full Node, what options should I enable so I can query and receive fully decoded transactions.

**Comment by huangsuyu** [comment]
hello, @YordanPavlov 

You can see the examples in golang here: https://github.com/binance-chain/node-binary/issues/53

**Comment by YordanPavlov** [comment]
Thank you for your answer. That will help, however I was thinking for a way to instruct the Node to decode it on server side and send it in the response. I saw the `?format=json` option mentioned in the docs for tx query. Also there is this:

> For example, below is the detail of a send transaction. Most of the fields are fixed, but the detail of msg varies with msg type, if you query with --format=json. 

In the docs here:
https://docs.binance.org/api-reference/dex-api/paths.html#transaction

Can that work? Also how can I enable HTTP API on my local node. 

Thank you for your time.

**Comment by huangsuyu** [comment]
Hello, @YordanPavlov 
You cannot operate your own HTTP API on your end, it's only provided by [accelerated nodes](https://docs.binance.org/faq.html#what-is-the-accelerated-node)

These accelerated nodes provide decoded transaction info.
