### ISSUE TITLE
404 HTTP API (Binance Chain HTTP API) response

### ISSUE THREAD

**Issue by amitsharma8891** [binance-chain/node-binary#98]
Hi,

I followed the documentation and started the full node. Also, I started the API server which is running at http://127.0.0.1:8080.

when I run `http://127.0.0.1:8080/version` it works but when I tried running:

`http://127.0.0.1:8080/api/v1/node-info` it throws 404 error.

Can anyone tell me where am I doing wrong?

Thanks

**Comment by huangsuyu** [comment]
Hello, @amitsharma8891 

Please refer to this doc about the available functions for API server: https://docs.binance.org/api-reference/api-server.html
